# -*- coding: utf-8 -*-
"""
Полностью дифференциальная модель (механика + пневматика) по схеме:
- Ц1 (4 цилиндра): двухступенчатый насос: атмосфера -> Ресивер1 -> Ресивер2
- Ц2 (4 цилиндра): третья ступень: Ресивер2 -> диагонали (с дросселями) -> Ресивер3 -> Аккумулятор
- Адаптивные клапана ресивера 3: Pmin/Pmid (сброс) и Pmax (предохранительный)

Состояние:
- Механика: z, phi, theta, z_w[4] + скорости (14 переменных)
- Пневматика: массы воздуха во всех узлах (N переменных)

Математика:
- Газ: идеальный, T=const (изотерма)
- Узлы-ёмкости: p = m R T / V
- Расходы: сжимаемый исток/дроссель (choked/subsonic), обратный клапан = диод с перепадом открытия
- Регулятор "после себя": открывает проток, если p_вниз < уставка
- Регулятор/клапан "до себя" (сброс): открывает проток, если p_вверх > уставка

Выход:
- Excel с KPI/расходами/энергией по дросселям + временные ряды.

Примечание:
Эта версия фокусируется на корректной топологии и дифференциальности модели.
Параметры (уставки, диаметры дросселей, объёмы) вынесены в словарь params и могут оптимизироваться.

(c) generated by ChatGPT
"""

from dataclasses import dataclass
import os
import math
import numpy as np
import pandas as pd
import re


# ---------------------------------------------------------------------
# База компонентов Camozzi (жёсткая привязка по месту)
# Источники:
# - VNR: серия обратных клапанов (Qn и min operating pressure) из официального PDF Camozzi VNR-ENG (2025/05)
# - SCO: серия двунаправленных дросселей (номинальные диаметры по портам) из официального PDF SCU/MCU/SVU/MVU/SCO/MCO (2025/04)
# ---------------------------------------------------------------------

CAMOZZI_VNR = {
    # код: {Qn [Nl/min] при 6 bar, ΔP=1 bar; минимальное рабочее давление (используем как перепад открытия), бар; максимальное давление, бар}
    "VNR-210-1/8":  {"Qn_Nl_min": 600.0,  "dp_откр_бар": 0.2,  "Pmax_бар": 10.0},   # G1/8
    "VNR-843-07":   {"Qn_Nl_min": 1400.0, "dp_откр_бар": 0.2,  "Pmax_бар": 10.0},   # G1/4
    "VNR-238-3/8":  {"Qn_Nl_min": 3000.0, "dp_откр_бар": 0.02, "Pmax_бар": 25.0},   # G3/8
    "VNR-212-1/2":  {"Qn_Nl_min": 5800.0, "dp_откр_бар": 0.02, "Pmax_бар": 25.0},   # G1/2
}

CAMOZZI_SCO = {
    # код: {номинальный диаметр, мм (максимальный); тип}
    "SCO 604-1/8":        {"d_max_мм": 2.0,  "тип": "двунаправленный дроссель (SCO)"},
    "SCO 606-1/4":        {"d_max_мм": 4.0,  "тип": "двунаправленный дроссель (SCO)"},
    "SCO 608-3/8":        {"d_max_мм": 7.0,  "тип": "двунаправленный дроссель (SCO)"},
    "SCO 610-1/2":        {"d_max_мм": 12.0, "тип": "двунаправленный дроссель (SCO)"},
    "SCO 604-1/8+2905":   {"d_max_мм": 2.0,  "тип": "дроссель с глушителем (SCO+2905)"},
    "SCO 606-1/4+2905":   {"d_max_мм": 4.0,  "тип": "дроссель с глушителем (SCO+2905)"},
}


# -------------------------
# Физические константы
# -------------------------
R_AIR = 287.0
T_AIR = 293.15

class RolloverException(RuntimeError):
    """Расчёт прерван: модель предсказала опрокидывание/невалидное состояние."""
    pass

GAMMA = 1.4
P_ATM = 101325.0

# Нормальные условия для пересчёта Qn [Nl/min] -> ṁ (по умолчанию)
# В промышленной практике Nl часто понимают как 0°C и 1 атм (101325 Па).
P_N_DEFAULT = 101325.0
T_N_DEFAULT = 273.15


# -------------------------
# Гладкие аппроксимации (для дифференцируемой динамики)
# -------------------------
def smooth_abs(x, eps: float):
    """Гладкий |x| ≈ sqrt(x^2 + eps^2). eps имеет те же единицы, что и x."""
    return np.sqrt(x*x + (eps*eps))

def smooth_pos(x, eps: float):
    """Гладкий max(0,x) через 0.5*(x + sqrt(x^2+eps^2))."""
    return 0.5 * (x + smooth_abs(x, eps))

def smooth_pos_grad(x, eps: float):
    """Производная smooth_pos по x: гладкий аналог Heaviside(x) в [0;1]."""
    return 0.5 * (1.0 + x / smooth_abs(x, eps))

def smooth_max(x, lo, eps: float):
    """Гладкий max(x, lo)."""
    return lo + smooth_pos(x - lo, eps)

def smooth_min(x, hi, eps: float):
    """Гладкий min(x, hi)."""
    return hi - smooth_pos(hi - x, eps)

def smooth_clip_with_grad(x, lo, hi, eps: float):
    """Гладкий clip(x, lo, hi) и его производная dy/dx.
    Возвращает (y, dy_dx).
    """
    x1 = smooth_max(x, lo, eps)
    dx1_dx = smooth_pos_grad(x - lo, eps)
    y = smooth_min(x1, hi, eps)
    dy_dx1 = smooth_pos_grad(hi - x1, eps)
    dy_dx = dy_dx1 * dx1_dx
    return y, dy_dx

# -------------------------
# Газодинамика (дроссели)
# -------------------------
def mdot_orifice(p_up: float, p_dn: float, A: float, Cd: float = 0.8) -> float:
    """Массовый расход через отверстие из p_up в p_dn (p_up>p_dn), кг/с."""
    if A <= 0.0:
        return 0.0
    if p_up <= 0.0 or p_dn <= 0.0:
        return 0.0
    if p_up <= p_dn:
        return 0.0

    pr = p_dn / p_up
    pr_crit = (2.0 / (GAMMA + 1.0)) ** (GAMMA / (GAMMA - 1.0))

    if pr <= pr_crit:
        # захлопывание (choked)
        return Cd * A * p_up * math.sqrt(GAMMA / (R_AIR * T_AIR)) * (2.0 / (GAMMA + 1.0)) ** ((GAMMA + 1.0) / (2.0 * (GAMMA - 1.0)))
    else:
        term = pr ** (2.0 / GAMMA) - pr ** ((GAMMA + 1.0) / GAMMA)
        term = max(term, 0.0)
        return Cd * A * p_up * math.sqrt(2.0 * GAMMA / (R_AIR * T_AIR * (GAMMA - 1.0)) * term)

def mdot_orifice_signed(p1: float, p2: float, A: float, Cd: float = 0.8) -> float:
    """Двусторонний дроссель: знак расхода зависит от перепада."""
    if p1 > p2:
        return mdot_orifice(p1, p2, A, Cd)
    elif p2 > p1:
        return -mdot_orifice(p2, p1, A, Cd)
    else:
        return 0.0

def area_from_Qn(Qn_Nl_min: float,
                 p_up_abs: float = None,
                 dp: float = None,
                 Cd: float = 0.8,
                 P_N: float = P_N_DEFAULT,
                 T_N: float = T_N_DEFAULT) -> float:
    """Подбор эквивалентной площади A по номинальному расходу Qn (Nl/min).

    ВАЖНО про Nl/min:
    - 'Nl' (normal litre) обычно означает пересчёт объёмного расхода к нормальным условиям.
      Во многих инженерных источниках нормальные условия принимают как 0°C и 1.01325 bar abs.
    - Чтобы не было скрытой ошибки ~5–10% по проводимости (из‑за ρ_N), условия N вынесены в P_N/T_N.

    Здесь делаем:
        Qn [Nl/min] -> Qn [m³/s] при нормальных условиях -> ṁ_N = ρ_N * Qn
    и подбираем A так, чтобы ṁ_orifice(p_up, p_dn, A) совпал с ṁ_N в паспортной точке (6 bar, ΔP=1 bar).
    """
    # плотность воздуха при нормальных условиях
    rho_N = float(P_N) / (R_AIR * float(T_N))

    # нормальный объёмный расход (м³/с)
    Qn_m3_s = (Qn_Nl_min / 1000.0) / 60.0
    mdot_N = rho_N * Qn_m3_s

    # Паспортная точка Camozzi: подача 6 bar (обычно избыточное) и ΔP=1 bar.
    if p_up_abs is None:
        p_up_abs = P_ATM + 6e5
    if dp is None:
        dp = 1e5
    p_dn_abs = max(P_ATM, p_up_abs - dp)

    base = mdot_orifice(p_up_abs, p_dn_abs, 1.0, Cd)
    if base <= 0.0:
        return 1e-6
    return mdot_N / base

def A_from_diam_mm(d_mm: float) -> float:
    return math.pi * (d_mm * 1e-3 / 2.0) ** 2

# -------------------------
# Сеть узлов/элементов
# -------------------------
@dataclass
class Node:
    name: str
    kind: str  # 'fixed', 'chamber', 'atmos'
    V0: float  # м3 (для chamber это мёртвый объём)
    corner: str = None
    chamber: str = None  # 'CAP'/'ROD'
    cyl: str = None      # 'C1'/'C2'

@dataclass
class Edge:
    name: str
    n1: int
    n2: int
    kind: str  # 'check','orifice','reg_after','relief'
    A: float
    dp_crack: float = 2000.0
    p_set: float = None
    Cd: float = 0.8
    group: str = None
    camozzi_код: str = ''
    A_макс: float = None   # для дросселя (по d_max)
    alpha: float = None    # 0..1 (для дросселя)


corner_order = ['ЛП', 'ПП', 'ЛЗ', 'ПЗ']

def build_network_full(params: dict):
    nodes = []
    node_index = {}
    def add_node(name, kind, V0, corner=None, chamber=None, cyl=None):
        idx = len(nodes)
        nodes.append(Node(name, kind, V0, corner, chamber, cyl))
        node_index[name] = idx
        return idx

    V_R1 = params.get('объём_ресивера_1', 0.0005)
    V_R2 = params.get('объём_ресивера_2', 0.0005)
    V_R3 = params.get('объём_ресивера_3', 0.0010)
    V_ACC = params.get('объём_аккумулятора', 0.0020)
    V_line = params.get('объём_линии', 2e-5)

    # Нормальные условия для параметров Qn [Nl/min] (можно переопределить в params)
    P_N = float(params.get('P_N_Па', P_N_DEFAULT))
    T_N = float(params.get('T_N_К', T_N_DEFAULT))

    add_node('АТМ', 'atmos', 1e-9)
    add_node('Ресивер1', 'fixed', V_R1)
    add_node('Ресивер2', 'fixed', V_R2)
    add_node('Ресивер3', 'fixed', V_R3)
    add_node('Аккумулятор', 'fixed', V_ACC)

    add_node('узел_после_рег_Pmin_питание_Р2', 'fixed', V_line)
    add_node('узел_после_предохран_Pmax', 'fixed', V_line)
    add_node('узел_после_рег_Pmid', 'fixed', V_line)
    add_node('узел_после_ОК_Pmid', 'fixed', V_line)
    add_node('узел_после_рег_Pmin_сброс', 'fixed', V_line)
    add_node('узел_после_ОК_Pmin', 'fixed', V_line)
    add_node('узел_после_рег_заряд_аккумулятора', 'fixed', V_line)

    V0_ch = params.get('мёртвый_объём_камеры', 15e-6)
    for c in corner_order:
        add_node(f'Ц1_{c}_БП', 'chamber', V0_ch, corner=c, chamber='CAP', cyl='C1')
        add_node(f'Ц1_{c}_ШП', 'chamber', V0_ch, corner=c, chamber='ROD', cyl='C1')
        add_node(f'Ц2_{c}_БП', 'chamber', V0_ch, corner=c, chamber='CAP', cyl='C2')
        add_node(f'Ц2_{c}_ШП', 'chamber', V0_ch, corner=c, chamber='ROD', cyl='C2')

    add_node('Магистраль_ЛП2_ПЗ2', 'fixed', V_line)
    add_node('Магистраль_ПП2_ЛЗ2', 'fixed', V_line)

    diag_pairs = [('ЛП', 'ПЗ', 'Магистраль_ЛП2_ПЗ2'), ('ПП', 'ЛЗ', 'Магистраль_ПП2_ЛЗ2')]
    conns = [('CAP', 'ROD'), ('ROD', 'CAP')]
    for a, b, _man in diag_pairs:
        for ch_a, ch_b in conns:
            add_node(f'узел_{a}{ch_a}_к_{b}{ch_b}_междуОКиДР', 'fixed', V_line)
            add_node(f'узел_{a}{ch_a}_к_{b}{ch_b}_послеДР', 'fixed', V_line)
            add_node(f'узел_{b}{ch_b}_к_{a}{ch_a}_междуОКиДР', 'fixed', V_line)
            add_node(f'узел_{b}{ch_b}_к_{a}{ch_a}_послеДР', 'fixed', V_line)

    edges = []
    def add_edge(name, n1_name, n2_name, kind, A, dp_crack=2000.0, p_set=None, Cd=0.8, group=None, camozzi_код='', A_макс=None, alpha=None):
        edges.append(Edge(name, node_index[n1_name], node_index[n2_name], kind, A, dp_crack, p_set, Cd, group, camozzi_код, A_макс, alpha))

    # Эквивалентные площади по конкретным Camozzi-кодам
    def A_по_VNR(код: str):
        d = CAMOZZI_VNR[код]
        return area_from_Qn(d["Qn_Nl_min"], P_N=P_N, T_N=T_N), d["dp_откр_бар"]*1e5

    def A_по_SCO(код: str, alpha: float):
        d = CAMOZZI_SCO[код]
        Amax = A_from_diam_mm(d["d_max_мм"])
        return alpha*Amax, Amax

    # Базовые настройки дросселей (0..1) — дальше это оптимизируемые параметры
    # Два дросселя (две линии) для раздельной настройки: CAP→ROD и ROD→CAP (условно: сжатие/отбой)
    alpha_дроссель_диагональ_CAP_ROD = params.get('открытие_дросселя_Ц2_CAP_в_ROD', 0.35)
    alpha_дроссель_диагональ_ROD_CAP = params.get('открытие_дросселя_Ц2_ROD_в_CAP', 0.35)
    alpha_дроссель_выхлоп_Pmin = params.get('открытие_дросселя_выхлоп_Pmin', 0.08)
    alpha_дроссель_выхлоп_Pmid = params.get('открытие_дросселя_выхлоп_Pmid', 0.18)
    alpha_дроссель_выхлоп_Pmax = params.get('открытие_дросселя_выхлоп_Pmax', 0.70)


    # -------------------------
    # Ц1: атмосфера -> Ресивер1 -> Ресивер2  (2 ступени)
    # -------------------------
    for c in corner_order:
        # Впуск: атмосфера -> бесштоковая полость Ц1
        A, dp = A_по_VNR("VNR-238-3/8")
        add_edge(f'обратный_клапан‑впуск‑атмосфера‑Ц1‑{c}‑бесштоковая',
                 'АТМ', f'Ц1_{c}_БП', 'check', A, dp, group='клапан', camozzi_код="VNR-238-3/8")

        # Выпуск ступени 1: Ц1 бесштоковая -> Ресивер1
        A, dp = A_по_VNR("VNR-238-3/8")
        add_edge(f'обратный_клапан‑выпуск‑Ц1‑{c}‑бесштоковая‑в‑Ресивер1',
                 f'Ц1_{c}_БП', 'Ресивер1', 'check', A, dp, group='клапан', camozzi_код="VNR-238-3/8")

        # Впуск ступени 2: Ресивер1 -> Ц1 штоковая
        A, dp = A_по_VNR("VNR-238-3/8")
        add_edge(f'обратный_клапан‑впуск‑Ресивер1‑в‑Ц1‑{c}‑штоковая',
                 'Ресивер1', f'Ц1_{c}_ШП', 'check', A, dp, group='клапан', camozzi_код="VNR-238-3/8")

        # Выпуск ступени 2: Ц1 штоковая -> Ресивер2
        A, dp = A_по_VNR("VNR-212-1/2")
        add_edge(f'обратный_клапан‑выпуск‑Ц1‑{c}‑штоковая‑в‑Ресивер2',
                 f'Ц1_{c}_ШП', 'Ресивер2', 'check', A, dp, group='клапан', camozzi_код="VNR-212-1/2")

    # Питание Ресивер2 из аккумулятора (регулятор "после себя" + обратный клапан)
    Pmin_feed = params.get('давление_Pmin_питание_Ресивер2', P_ATM + 2e5)
    A, dp = A_по_VNR("VNR-238-3/8")
    add_edge('регулятор‑после‑себя‑Pmin‑питание‑Ресивер2‑из‑Аккумулятор',
             'Аккумулятор', 'узел_после_рег_Pmin_питание_Р2', 'reg_after', A, dp, p_set=Pmin_feed,
             group='регулятор', camozzi_код='MC104-R00 (Series MC)')

    # Обратный клапан после регулятора (чтобы Р2 не сливался в аккумулятор)
    A, dp = A_по_VNR("VNR-238-3/8")
    add_edge('обратный_клапан‑питание‑Ресивер2‑из‑узла‑после‑регулятора',
             'узел_после_рег_Pmin_питание_Р2', 'Ресивер2', 'check', A, dp, group='клапан', camozzi_код="VNR-238-3/8")

    # -------------------------
    # Ц2: впуск из Ресивер2 + диагонали (дроссели) + сбор в Ресивер3
    # -------------------------
    for c in corner_order:
        # Впуск Р2 -> Ц2 (обе полости). Здесь используем 1/4 (реалистично под D50), но с dp=0.2 бар.
        A, dp = A_по_VNR("VNR-843-07")
        add_edge(f'обратный_клапан‑впуск‑Ресивер2‑в‑Ц2‑{c}‑бесштоковая',
                 'Ресивер2', f'Ц2_{c}_БП', 'check', A, dp, group='клапан', camozzi_код="VNR-843-07")
        A, dp = A_по_VNR("VNR-843-07")
        add_edge(f'обратный_клапан‑впуск‑Ресивер2‑в‑Ц2‑{c}‑штоковая',
                 'Ресивер2', f'Ц2_{c}_ШП', 'check', A, dp, group='клапан', camozzi_код="VNR-843-07")

    def ch_node(c, ch):
        return f'Ц2_{c}_БП' if ch == 'CAP' else f'Ц2_{c}_ШП'

    # Диагонали: соединения КАП<->ШТОК, как вы описали (все штоки вниз, перекрёст делаем связями камер)
    for a, b, man in diag_pairs:
        for ch_a, ch_b in conns:
            N_ab = f'узел_{a}{ch_a}_к_{b}{ch_b}_междуОКиДР'
            M_ab = f'узел_{a}{ch_a}_к_{b}{ch_b}_послеДР'
            N_ba = f'узел_{b}{ch_b}_к_{a}{ch_a}_междуОКиДР'
            M_ba = f'узел_{b}{ch_b}_к_{a}{ch_a}_послеДР'

            # --- направление a -> b ---
            # 1) из камеры a через обратный клапан в узел между ОК и ДР
            A, dp = A_по_VNR("VNR-843-07")
            add_edge(f'обратный_клапан‑выход‑из‑Ц2‑{a}‑{ch_a}‑в‑диагональ‑к‑{b}‑{ch_b}',
                     ch_node(a, ch_a), N_ab, 'check', A, dp, group='клапан', camozzi_код="VNR-843-07")

            # 2) из узла между ОК и ДР — ответвление в магистраль (к Р3) через обратный клапан (между ОК и ДР!)
            A, dp = A_по_VNR("VNR-238-3/8")
            add_edge(f'обратный_клапан‑сбор‑в‑магистраль‑{man}‑из‑узла‑{a}{ch_a}к{b}{ch_b}',
                     N_ab, man, 'check', A, dp, group='клапан', camozzi_код="VNR-238-3/8")

            # 3) из узла между ОК и ДР — через дроссель (компр/отбой) к другому цилиндру
            alpha_line = alpha_дроссель_диагональ_CAP_ROD if (ch_a == "CAP" and ch_b == "ROD") else alpha_дроссель_диагональ_ROD_CAP
            A_eff, Amax = A_по_SCO("SCO 606-1/4", alpha_line)
            add_edge(f'дроссель‑диагональ‑Ц2‑линия_{ch_a}→{ch_b}‑{a}{ch_a}→{b}{ch_b}',
                     N_ab, M_ab, 'orifice', A_eff, dp_crack=0.0, group='дроссель',
                     camozzi_код="SCO 606-1/4", A_макс=Amax, alpha=alpha_line)

            # 4) после дросселя — через обратный клапан в камеру b
            A, dp = A_по_VNR("VNR-843-07")
            add_edge(f'обратный_клапан‑вход‑в‑Ц2‑{b}‑{ch_b}‑из‑диагонали‑{a}{ch_a}→{b}{ch_b}',
                     M_ab, ch_node(b, ch_b), 'check', A, dp, group='клапан', camozzi_код="VNR-843-07")

            # --- направление b -> a (симметрично) ---
            A, dp = A_по_VNR("VNR-843-07")
            add_edge(f'обратный_клапан‑выход‑из‑Ц2‑{b}‑{ch_b}‑в‑диагональ‑к‑{a}‑{ch_a}',
                     ch_node(b, ch_b), N_ba, 'check', A, dp, group='клапан', camozzi_код="VNR-843-07")

            A, dp = A_по_VNR("VNR-238-3/8")
            add_edge(f'обратный_клапан‑сбор‑в‑магистраль‑{man}‑из‑узла‑{b}{ch_b}к{a}{ch_a}',
                     N_ba, man, 'check', A, dp, group='клапан', camozzi_код="VNR-238-3/8")

            alpha_line = alpha_дроссель_диагональ_CAP_ROD if (ch_b == "CAP" and ch_a == "ROD") else alpha_дроссель_диагональ_ROD_CAP
            A_eff, Amax = A_по_SCO("SCO 606-1/4", alpha_line)
            add_edge(f'дроссель‑диагональ‑Ц2‑линия_{ch_b}→{ch_a}‑{b}{ch_b}→{a}{ch_a}',
                     N_ba, M_ba, 'orifice', A_eff, dp_crack=0.0, group='дроссель',
                     camozzi_код="SCO 606-1/4", A_макс=Amax, alpha=alpha_line)

            A, dp = A_по_VNR("VNR-843-07")
            add_edge(f'обратный_клапан‑вход‑в‑Ц2‑{a}‑{ch_a}‑из‑диагонали‑{b}{ch_b}→{a}{ch_a}',
                     M_ba, ch_node(a, ch_a), 'check', A, dp, group='клапан', camozzi_код="VNR-843-07")

    # Магистрали -> Ресивер3
    A, dp = A_по_VNR("VNR-212-1/2")
    add_edge('обратный_клапан‑магистраль‑ЛП2ПЗ2‑в‑Ресивер3',
             'Магистраль_ЛП2_ПЗ2', 'Ресивер3', 'check', A, dp, group='клапан', camozzi_код="VNR-212-1/2")
    A, dp = A_по_VNR("VNR-212-1/2")
    add_edge('обратный_клапан‑магистраль‑ПП2ЛЗ2‑в‑Ресивер3',
             'Магистраль_ПП2_ЛЗ2', 'Ресивер3', 'check', A, dp, group='клапан', camozzi_код="VNR-212-1/2")

    # Ресивер3 -> Аккумулятор: регулятор "до себя" (ограничивает/задаёт порог зарядки) + обратный клапан (только заряд)
    Pзаряд_акк = params.get('давление_Pзаряд_аккумулятора_из_Ресивер3', P_ATM + 8e5)
    A_reg, _dp = A_по_VNR("VNR-212-1/2")  # по проходу как крупный
    add_edge('регулятор_до_себя_заряд_аккумулятора_из_Ресивер3',
             'Ресивер3', 'узел_после_рег_заряд_аккумулятора', 'relief', A_reg, dp_crack=0.0, p_set=Pзаряд_акк,
             group='регулятор', camozzi_код='VMR 1/8-B10')

    A, dp = A_по_VNR("VNR-212-1/2")
    add_edge('обратный_клапан‑заряд‑аккумулятора‑после_регулятора',
             'узел_после_рег_заряд_аккумулятора', 'Аккумулятор', 'check', A, dp, group='клапан', camozzi_код="VNR-212-1/2")
# -------------------------
    # Сброс/предохранение Ресивер3 -> АТМ  (адаптивность)
    # -------------------------
    Pmax = params.get('давление_Pmax_предохран', P_ATM + 8e5)
    Pmid = params.get('давление_Pmid_сброс', P_ATM + 6.8e5)
    Pmin_rel = params.get('давление_Pmin_сброс', P_ATM + 4.5e5)

    # Предохранительный клапан (эквивалент Camozzi VMR 1/8-B10 как "overpressure exhaust valve")
    # В модели это "relief" элемент: открывается при p(Р3) > Pmax
    A, _dp = A_по_VNR("VNR-212-1/2")  # по пропускной как крупный проход
    add_edge('клапан_предохранительный_Pmax_Ресивер3→узел',
             'Ресивер3', 'узел_после_предохран_Pmax', 'relief', A, dp_crack=0.0, p_set=Pmax,
             group='клапан', camozzi_код='VMR 1/8-B10')

    # Дросселирование на выход в атмосферу (SCO + 2905)
    A_eff, Amax = A_по_SCO("SCO 606-1/4", alpha_дроссель_выхлоп_Pmax)
    add_edge('дроссель_выхлоп_Pmax',
             'узел_после_предохран_Pmax', 'АТМ', 'orifice', A_eff, dp_crack=0.0,
             group='выхлоп', camozzi_код="SCO 606-1/4", A_макс=Amax, alpha=alpha_дроссель_выхлоп_Pmax)

    # Сброс Pmid: регулятор "до себя" (открывается при p(Р3) > Pmid) → обратный клапан → дроссель → атмосфера
    A, _dp = A_по_VNR("VNR-238-3/8")
    add_edge('регулятор_до_себя_Pmid_сброс',
             'Ресивер3', 'узел_после_рег_Pmid', 'relief', A, dp_crack=0.0, p_set=Pmid,
             group='регулятор', camozzi_код='VMR 1/8-B10')

    A, dp = A_по_VNR("VNR-238-3/8")
    add_edge('обратный_клапан_Pmid_к_выхлопу',
             'узел_после_рег_Pmid', 'узел_после_ОК_Pmid', 'check', A, dp,
             group='клапан', camozzi_код="VNR-238-3/8")

    A_eff, Amax = A_по_SCO("SCO 604-1/8", alpha_дроссель_выхлоп_Pmid)
    add_edge('дроссель_выхлоп_Pmid',
             'узел_после_ОК_Pmid', 'АТМ', 'orifice', A_eff, dp_crack=0.0,
             group='выхлоп', camozzi_код="SCO 604-1/8", A_макс=Amax, alpha=alpha_дроссель_выхлоп_Pmid)

    # Сброс Pmin: то же самое, но уставка ниже
    A, _dp = A_по_VNR("VNR-238-3/8")
    add_edge('регулятор_до_себя_Pmin_сброс',
             'Ресивер3', 'узел_после_рег_Pmin_сброс', 'relief', A, dp_crack=0.0, p_set=Pmin_rel,
             group='регулятор', camozzi_код='VMR 1/8-B10')

    A, dp = A_по_VNR("VNR-238-3/8")
    add_edge('обратный_клапан_Pmin_к_выхлопу',
             'узел_после_рег_Pmin_сброс', 'узел_после_ОК_Pmin', 'check', A, dp,
             group='клапан', camozzi_код="VNR-238-3/8")

    A_eff, Amax = A_по_SCO("SCO 604-1/8", alpha_дроссель_выхлоп_Pmin)
    add_edge('дроссель_выхлоп_Pmin',
             'узел_после_ОК_Pmin', 'АТМ', 'orifice', A_eff, dp_crack=0.0,
             group='выхлоп', camozzi_код="SCO 604-1/8", A_макс=Amax, alpha=alpha_дроссель_выхлоп_Pmin)

# Матрица инцидентности
    N = len(nodes)
    E = len(edges)
    B = np.zeros((N, E))
    for ei, e in enumerate(edges):
        B[e.n1, ei] -= 1.0
        B[e.n2, ei] += 1.0

    return nodes, node_index, edges, B

# -------------------------
# Моделирование
# -------------------------

# ---------------------------------------------------------------------------
# Тест‑сценарии из default_suite.json (suite/UI формат) → входные функции
# ---------------------------------------------------------------------------
def _smoothstep01(x: float) -> float:
    """Гладкая стыковка 0→1 (C1), x∈[0,1]."""
    if x <= 0.0:
        return 0.0
    if x >= 1.0:
        return 1.0
    return x * x * (3.0 - 2.0 * x)

def _step_with_ramp(t: float, t0: float, val: float, ramp_s: float) -> float:
    """Ступенька, но с плавным включением за ramp_s секунд."""
    if t <= t0:
        return 0.0
    if ramp_s is None or ramp_s <= 0.0:
        return float(val)
    x = (t - t0) / float(ramp_s)
    if x >= 1.0:
        return float(val)
    return float(val) * _smoothstep01(x)

def _bump_with_smooth(t: float, t0: float, dur: float, A: float, smooth_frac: float = 0.2) -> float:
    """Прямоугольная кочка A на интервале [t0, t0+dur] с плавными фронтами."""
    if dur is None:
        return 0.0
    dur = float(dur)
    if dur <= 0.0:
        return 0.0
    t1 = float(t0)
    t2 = t1 + dur
    if t < t1 or t > t2:
        return 0.0

    sf = float(smooth_frac) if smooth_frac is not None else 0.0
    sf = max(0.0, min(0.49, sf))
    ramp = max(1e-9, sf * dur)

    # Включение
    if t < t1 + ramp:
        x = (t - t1) / ramp
        return float(A) * _smoothstep01(x)

    # Выключение
    if t > t2 - ramp:
        x = (t2 - t) / ramp
        return float(A) * _smoothstep01(x)

    return float(A)

def _compile_suite_test_inputs(test: dict, params: dict):
    """Поддержка 'тип' из suite/UI: строит ax_func/ay_func/road_func если их нет.
    Возвращает dict с функциями (может быть пустым).
    """
    if not isinstance(test, dict):
        return {}
    ttype = str(test.get("тип", "")).strip()
    if not ttype:
        return {}

    # Если пользователь/скрипт уже передал явные функции — не трогаем.
    has_any = any(callable(test.get(k, None)) for k in ("ax_func", "ay_func", "road_func"))
    if has_any:
        return {}

    add = {}

    # Геометрия (для диагональной кочки)
    # ABSOLUTE LAW: canonical keys only ("база" / "колея").
    # Defaults match pneumo_solver_ui/default_base.json.
    L = float(params.get("база", 1.5) or 1.5)      # колесная база
    W = float(params.get("колея", 1.0) or 1.0)     # колея

    # Общие параметры сглаживания
    smooth_frac = float(test.get("доля_плавной_стыковки", 0.2) or 0.2)

    if ttype == "инерция_крен":
        ay = float(test.get("ay_м_с2", test.get("ay", 0.0)) or 0.0)
        t_step = float(test.get("t_step", 0.0) or 0.0)
        ramp = float(test.get("ramp_s", 0.05) or 0.05)
        add["ay_func"] = lambda t, ay=ay, t0=t_step, ramp=ramp: _step_with_ramp(t, t0, ay, ramp)
        add["ax_func"] = lambda t: 0.0
        add["road_func"] = lambda t: np.zeros(4, dtype=float)

    elif ttype == "инерция_тангаж":
        ax = float(test.get("ax_м_с2", test.get("ax", 0.0)) or 0.0)
        t_step = float(test.get("t_step", 0.0) or 0.0)
        ramp = float(test.get("ramp_s", 0.05) or 0.05)
        add["ax_func"] = lambda t, ax=ax, t0=t_step, ramp=ramp: _step_with_ramp(t, t0, ax, ramp)
        add["ay_func"] = lambda t: 0.0
        add["road_func"] = lambda t: np.zeros(4, dtype=float)

    elif ttype == "микро_синфаза":
        A = float(test.get("A_м", test.get("A", 0.0)) or 0.0)
        f = float(test.get("f_Гц", test.get("f", 1.0)) or 1.0)
        w = 2.0 * math.pi * f
        add["road_func"] = lambda t, A=A, w=w: (A * math.sin(w * t)) * np.ones(4, dtype=float)
        add["ax_func"] = lambda t: 0.0
        add["ay_func"] = lambda t: 0.0

    elif ttype == "микро_разнофаза":
        A = float(test.get("A_м", test.get("A", 0.0)) or 0.0)
        f = float(test.get("f_Гц", test.get("f", 1.0)) or 1.0)
        w = 2.0 * math.pi * f
        # Диагональная разнофаза (относительно противоположных углов): (ЛП+ПЗ) в одной фазе, (ПП+ЛЗ) в противофазе
        # порядок углов: [ЛП, ПП, ЛЗ, ПЗ]
        s = np.array([+1.0, -1.0, -1.0, +1.0], dtype=float)
        add["road_func"] = lambda t, A=A, w=w, s=s: (A * math.sin(w * t)) * s
        add["ax_func"] = lambda t: 0.0
        add["ay_func"] = lambda t: 0.0

    elif ttype == "кочка_одно_колесо":
        A = float(test.get("A_м", test.get("A", 0.0)) or 0.0)
        t0 = float(test.get("t0", 0.0) or 0.0)
        dur = float(test.get("dur", 0.0) or 0.0)
        # Поддерживаем и "idx" (0=ЛП,1=ПП,2=ЛЗ,3=ПЗ), и "колесо" (строкой).
        idx_map = {"ЛП": 0, "ПП": 1, "ЛЗ": 2, "ПЗ": 3}
        i = None
        try:
            if test.get("idx", None) is not None:
                i = int(test.get("idx"))
        except Exception:
            i = None
        if i is None:
            wheel = str(test.get("колесо", "ЛП")).strip().upper()
            i = idx_map.get(wheel, 0)
        i = max(0, min(3, int(i)))

        def road_func(t, i=i, A=A, t0=t0, dur=dur, sf=smooth_frac):
            v = np.zeros(4, dtype=float)
            v[i] = _bump_with_smooth(t, t0, dur, A, sf)
            return v

        add["road_func"] = road_func
        add["ax_func"] = lambda t: 0.0
        add["ay_func"] = lambda t: 0.0

    elif ttype == "кочка_диагональ":
        A = float(test.get("A_м", test.get("A", 0.0)) or 0.0)
        t0 = float(test.get("t0", 0.0) or 0.0)
        dur = float(test.get("dur", 0.0) or 0.0)
        # скорость авто вдоль оси (для времени прихода диагональной кочки)
        v = float(test.get("vx0_м_с", 0.0) or 0.0)  # ABSOLUTE LAW: canonical speed key
        ang = float(test.get("угол_град", test.get("angle_град", test.get("angle_deg", 0.0))) or 0.0)
        alpha = math.radians(ang)

        # Позиции колес относительно ЦМ (x вперед, y влево)
        xs = np.array([+L/2, +L/2, -L/2, -L/2], dtype=float)
        ys = np.array([+W/2, -W/2, +W/2, -W/2], dtype=float)

        if abs(v) < 1e-9:
            t_hits = np.full(4, t0, dtype=float)
        else:
            # Модель пересечения диагональной линии кочки (приближение):
            # t_hit = offset + (-(x + y*tan(alpha)) / v), offset выбрано так,
            # чтобы ЛП (0) имела t_hit = t0.
            tau = -(xs + ys * math.tan(alpha)) / v
            offset = t0 - tau[0]
            t_hits = offset + tau

        def road_func(t, A=A, dur=dur, t_hits=t_hits, sf=smooth_frac):
            return np.array([_bump_with_smooth(t, th, dur, A, sf) for th in t_hits], dtype=float)

        add["road_func"] = road_func
        add["ax_func"] = lambda t: 0.0
        add["ay_func"] = lambda t: 0.0

    elif ttype == "комбо_крен_плюс_микро":
        ay = float(test.get("ay_м_с2", test.get("ay", 0.0)) or 0.0)
        t_step = float(test.get("t_step", 0.0) or 0.0)
        ramp = float(test.get("ramp_s", 0.05) or 0.05)
        A = float(test.get("A_м", test.get("A", 0.0)) or 0.0)
        f = float(test.get("f_Гц", test.get("f", 1.0)) or 1.0)
        w = 2.0 * math.pi * f
        add["ay_func"] = lambda t, ay=ay, t0=t_step, ramp=ramp: _step_with_ramp(t, t0, ay, ramp)
        add["ax_func"] = lambda t: 0.0
        add["road_func"] = lambda t, A=A, w=w: (A * math.sin(w * t)) * np.ones(4, dtype=float)

    # Если не распознали — ничего не добавляем.
    return add


def simulate(params: dict, test: dict, dt: float = 1e-3, t_end: float = 3.0, record_full: bool = False):
    nodes, node_index, edges, B = build_network_full(params)

    # --- Scheme integrity (topology lock) ---
    # Схема по ТЗ неизменяема: разрешена только калибровка параметров.
    try:
        from .scheme_integrity import assert_fingerprint, assert_camozzi_only
    except Exception:
        # when executed as a script (sys.path hack)
        from scheme_integrity import assert_fingerprint, assert_camozzi_only

    if bool(params.get('enforce_scheme_integrity', True)):
        fp_file = str(params.get('scheme_fingerprint_file', 'scheme_fingerprint.json'))
        if not os.path.isabs(fp_file):
            fp_file = os.path.join(os.path.dirname(__file__), fp_file)
        assert_fingerprint(nodes, edges, fp_file)

    if bool(params.get('enforce_camozzi_only', True)):
        pp_file = str(params.get('паспорт_компонентов_json', params.get('passport_components_json', 'component_passport.json')))
        if not os.path.isabs(pp_file):
            pp_file = os.path.join(os.path.dirname(__file__), pp_file)
        assert_camozzi_only(edges, pp_file)
    N = len(nodes)
    E = len(edges)
    # -------------------------------------------------------------
    # Helpers: безопасное чтение параметров (None/str -> float/bool)
    # -------------------------------------------------------------
    def _pfloat(key: str, default: float) -> float:
        v = params.get(key, default)
        if v is None:
            return float(default)
        try:
            return float(v)
        except Exception:
            return float(default)

    def _pbool(key: str, default: bool = False) -> bool:
        v = params.get(key, default)
        if v is None:
            return bool(default)
        return bool(v)

    def _pstr(key: str, default: str) -> str:
        v = params.get(key, default)
        if v is None:
            return str(default)
        return str(v)


    # -------------------------------------------------------------
    # Режим сглаживания (для дифференцируемости/градиентной оптимизации)
    # По умолчанию (smooth_dynamics=False) поведение совпадает с исходником.
    # -------------------------------------------------------------
    smooth_dynamics = bool(params.get('smooth_dynamics', False))
    smooth_mechanics = bool(params.get('smooth_mechanics', smooth_dynamics))
    smooth_stroke = bool(params.get('smooth_stroke', smooth_mechanics))
    smooth_contacts = bool(params.get('smooth_contacts', smooth_mechanics))
    smooth_spring = bool(params.get('smooth_spring', smooth_mechanics))
    smooth_pressure_floor = bool(params.get('smooth_pressure_floor', smooth_dynamics))

    # Если s клипуется по ходу штока, то физически корректно иметь ds/dt=0 на границах.
    # В исходнике было s=clip(...), но s_dot считался без учёта клипа.
    # Чтобы не менять поведение "по умолчанию", включается отдельным флагом.
    consistent_stroke_kinematics = bool(params.get('consistent_stroke_kinematics', False))

    # Параметры сглаживания (в тех же единицах, что аргумент)
    smooth_eps_pos_m = float(params.get('smooth_eps_pos_m', 1e-4))       # ~0.1 мм
    smooth_eps_vel_mps = float(params.get('smooth_eps_vel_mps', 1e-3))   # ~1 мм/с
    smooth_eps_mass_kg = float(params.get('smooth_eps_mass_kg', 1e-8))
    smooth_eps_vol_m3 = float(params.get('smooth_eps_vol_m3', 1e-12))

    smooth_eps_pos_m = max(1e-12, smooth_eps_pos_m)
    smooth_eps_vel_mps = max(1e-12, smooth_eps_vel_mps)
    smooth_eps_mass_kg = max(1e-18, smooth_eps_mass_kg)
    smooth_eps_vol_m3 = max(1e-18, smooth_eps_vol_m3)

    # Геометрия шасси
    # ABSOLUTE LAW: canonical keys only.
    wheelbase = float(params.get('база', 1.5) or 1.5)
    track = float(params.get('колея', 1.0) or 1.0)
    x_pos = np.array([ wheelbase/2,  wheelbase/2, -wheelbase/2, -wheelbase/2])
    y_pos = np.array([ track/2, -track/2,  track/2, -track/2])

    # Массы
    m_body = params.get('масса_рамы', 600.0)
    m_w = params.get('масса_неподрессоренная_на_угол', 15.0)
    g = 9.81

    # Габариты рамы (для момента инерции) — 1/2/6, ширина=0.3*колеи
    W = params.get('ширина_рамы', 0.3*track)
    H = params.get('высота_рамы', 2*W)
    L = params.get('длина_рамы', 6*W)
    I_roll = (1.0/12.0) * m_body * (W**2 + H**2)
    I_pitch= (1.0/12.0) * m_body * (L**2 + H**2)

    # Грубая оценка критического угла опрокидывания (проекция ЦМ выходит за опору)
    h_cg = float(params.get('высота_центра_масс', H/2.0))
    phi_crit = math.atan((track/2.0)/max(1e-6, h_cg))
    theta_crit = math.atan((wheelbase/2.0)/max(1e-6, h_cg))

    # Аварийный предел для остановки интегрирования (чтобы не улетать в невалидную геометрию).
    # Критические углы (phi_crit/theta_crit) используем как KPI («запас до пробоя»), а не как стоп.
    phi_abort_deg = float(params.get('аварийный_предел_крен_град', 85.0))
    theta_abort_deg = float(params.get('аварийный_предел_тангаж_град', 85.0))
    phi_abort = math.radians(phi_abort_deg)
    theta_abort = math.radians(theta_abort_deg)

    k_tire = params.get('жёсткость_шины', 200000.0)
    c_tire = params.get('демпфирование_шины', 2000.0)
    # Нелинейная пружина: табличная (кусочно-линейная) характеристика
    # delta = z_колеса - z_рамы_в_углу (м): delta>0 = сжатие подвески
    табл_пруж_ход_мм = np.array(params.get('пружина_таблица_ход_мм', [-125, -80, -40, -20, 0, 20, 50, 80, 125]), dtype=float)
    табл_пруж_сила_Н = np.array(params.get('пружина_таблица_сила_Н', [-1200, -900, -500, -200, 0, 400, 1200, 2200, 4000]), dtype=float)
    масштаб_пружины = float(params.get('пружина_масштаб', 1.0))
    табл_пруж_ход_м = табл_пруж_ход_мм * 1e-3

    # ВАЖНО: пружина односторонняя (только на сжатие).
    # Если в базе случайно заданы отрицательные точки — в модели их игнорируем.
    mask = (табл_пруж_ход_м >= 0.0) & (табл_пруж_сила_Н >= 0.0)
    if np.any(mask):
        табл_пруж_ход_м = табл_пруж_ход_м[mask]
        табл_пруж_сила_Н = табл_пруж_сила_Н[mask]
    order = np.argsort(табл_пруж_ход_м)
    табл_пруж_ход_м = табл_пруж_ход_м[order]
    табл_пруж_сила_Н = tab_F = np.maximum.accumulate(табл_пруж_сила_Н[order])

        # Геометрия цилиндров (Camozzi)
    D1 = _pfloat('диаметр_поршня_Ц1', 0.032)
    d1 = _pfloat('диаметр_штока_Ц1', 0.016)
    D2 = _pfloat('диаметр_поршня_Ц2', 0.050)
    d2 = _pfloat('диаметр_штока_Ц2', 0.014)

    A1_cap = math.pi*(D1/2)**2
    A1_rod = A1_cap - math.pi*(d1/2)**2
    A2_cap = math.pi*(D2/2)**2
    A2_rod = A2_cap - math.pi*(d2/2)**2

    # Ход штока: legacy (один на всё) + раздельные ходы (4 группы: Ц1/Ц2 × перед/зад)
    L_stroke_default = _pfloat('ход_штока', 0.250)

    L_stroke_C1_front = _pfloat('ход_штока_Ц1_перед_м', L_stroke_default)
    L_stroke_C1_rear  = _pfloat('ход_штока_Ц1_зад_м',   L_stroke_default)
    L_stroke_C2_front = _pfloat('ход_штока_Ц2_перед_м', L_stroke_default)
    L_stroke_C2_rear  = _pfloat('ход_штока_Ц2_зад_м',   L_stroke_default)

    stroke_C1 = np.array([L_stroke_C1_front, L_stroke_C1_front, L_stroke_C1_rear, L_stroke_C1_rear], dtype=float)
    stroke_C2 = np.array([L_stroke_C2_front, L_stroke_C2_front, L_stroke_C2_rear, L_stroke_C2_rear], dtype=float)

    s0_C1 = 0.5 * stroke_C1
    s0_C2 = 0.5 * stroke_C2

    # Режим механической кинематики:
    #  - 'legacy' : как в базовой версии (s = s0 - delta, MR=1)
    #  - 'dw2d'   : упрощённая геометрия установки цилиндров в плоскости Y–Z (double-wishbone-like)
    mech_kin = _pstr('механика_кинематика', 'dw2d').strip().lower()
    if mech_kin not in ('legacy', 'dw2d'):
        mech_kin = 'dw2d'

    # Геометрия креплений цилиндров (12 параметров из контекста проекта):
    # A) верхние шарниры по Y (разнос между лев/прав) — 4
    # B) верхние шарниры по Z (высота относительно рамы) — 4
    # C) нижний шарнир на рычаге (доля длины) — 4
    # Значения здесь по умолчанию приблизительные и должны быть уточнены по реальной геометрии.
    top_C1_front_span = _pfloat('верх_Ц1_перед_между_ЛП_ПП_м', float(W))
    top_C2_front_span = _pfloat('верх_Ц2_перед_между_ЛП_ПП_м', float(W))
    top_C1_rear_span  = _pfloat('верх_Ц1_зад_между_ЛЗ_ПЗ_м',   float(W))
    top_C2_rear_span  = _pfloat('верх_Ц2_зад_между_ЛЗ_ПЗ_м',   float(W))

    top_C1_front_z = _pfloat('верх_Ц1_перед_z_относительно_рамы_м', float(H))
    top_C2_front_z = _pfloat('верх_Ц2_перед_z_относительно_рамы_м', float(H))
    top_C1_rear_z  = _pfloat('верх_Ц1_зад_z_относительно_рамы_м',   float(H))
    top_C2_rear_z  = _pfloat('верх_Ц2_зад_z_относительно_рамы_м',   float(H))

    low_C1_front_frac = _pfloat('низ_Ц1_перед_доля_рычага', 0.70)
    low_C2_front_frac = _pfloat('низ_Ц2_перед_доля_рычага', 0.70)
    low_C1_rear_frac  = _pfloat('низ_Ц1_зад_доля_рычага',   0.70)
    low_C2_rear_frac  = _pfloat('низ_Ц2_зад_доля_рычага',   0.70)

    top_span_C1 = np.array([top_C1_front_span, top_C1_front_span, top_C1_rear_span, top_C1_rear_span], dtype=float)
    top_span_C2 = np.array([top_C2_front_span, top_C2_front_span, top_C2_rear_span, top_C2_rear_span], dtype=float)
    top_z_C1 = np.array([top_C1_front_z, top_C1_front_z, top_C1_rear_z, top_C1_rear_z], dtype=float)
    top_z_C2 = np.array([top_C2_front_z, top_C2_front_z, top_C2_rear_z, top_C2_rear_z], dtype=float)
    low_frac_C1 = np.array([low_C1_front_frac, low_C1_front_frac, low_C1_rear_frac, low_C1_rear_frac], dtype=float)
    low_frac_C2 = np.array([low_C2_front_frac, low_C2_front_frac, low_C2_rear_frac, low_C2_rear_frac], dtype=float)

    # Предварительный расчёт Y координат креплений (в body frame в точке колеса)
    sign_y = np.sign(y_pos)
    sign_y[sign_y == 0.0] = 1.0
    y_top_C1 = sign_y * 0.5 * top_span_C1
    y_top_C2 = sign_y * 0.5 * top_span_C2
    y_bot_C1 = low_frac_C1 * y_pos
    y_bot_C2 = low_frac_C2 * y_pos

    dy_C1 = y_top_C1 - y_bot_C1
    dy_C2 = y_top_C2 - y_bot_C2

    # Опорная длина цилиндра при delta=0 (для калибровки s≈mid при нулевом ходе)
    L0_C1 = np.sqrt(dy_C1**2 + top_z_C1**2)
    L0_C2 = np.sqrt(dy_C2**2 + top_z_C2**2)


        # Массивы камер (учёт разных ходов Ц1/Ц2 и перед/зад)
    V0_vec = np.array([n.V0 for n in nodes], dtype=float)
    chamber_indices = []
    chamber_corner = []
    chamber_cyl_id = []   # 1 для C1, 2 для C2
    chamber_sign = []
    chamber_area = []
    chamber_offset = []
    chamber_stroke = []
    for i, n in enumerate(nodes):
        if n.kind == 'chamber':
            ci = corner_order.index(n.corner)
            is_c1 = (n.cyl == 'C1')
            cyl_id = 1 if is_c1 else 2
            stroke_i = float(stroke_C1[ci] if is_c1 else stroke_C2[ci])
            chamber_indices.append(i)
            chamber_corner.append(ci)
            chamber_cyl_id.append(cyl_id)

            if is_c1:
                A = A1_cap if n.chamber == 'CAP' else A1_rod
            else:
                A = A2_cap if n.chamber == 'CAP' else A2_rod

            if n.chamber == 'CAP':
                sign = +1.0
                offset = n.V0
            else:
                sign = -1.0
                # В rod-полости объём при s=0 должен быть максимальным => +A*stroke
                offset = n.V0 + A * stroke_i

            chamber_sign.append(sign)
            chamber_area.append(A)
            chamber_offset.append(offset)
            chamber_stroke.append(stroke_i)

    chamber_indices = np.array(chamber_indices, dtype=int)
    chamber_corner = np.array(chamber_corner, dtype=int)
    chamber_cyl_id = np.array(chamber_cyl_id, dtype=int)
    chamber_sign = np.array(chamber_sign, dtype=float)
    chamber_area = np.array(chamber_area, dtype=float)
    chamber_offset = np.array(chamber_offset, dtype=float)
    chamber_stroke = np.array(chamber_stroke, dtype=float)


    # -------------------------
    # Начальные давления
    # -------------------------
    Pmin_abs = params.get('давление_Pmin_сброс', P_ATM + 4.5e5)
    Pacc_abs = params.get('начальное_давление_аккумулятора', P_ATM + 6e5)

    p0 = np.ones(N) * Pmin_abs
    p0[node_index['АТМ']] = P_ATM
    p0[node_index['Ресивер1']] = P_ATM
    p0[node_index['Аккумулятор']] = Pacc_abs
    for c in corner_order:
        p0[node_index[f'Ц1_{c}_БП']] = P_ATM
    for name in ['узел_после_предохран_Pmax','узел_после_рег_Pmid','узел_после_ОК_Pmid','узел_после_рег_Pmin_сброс','узел_после_ОК_Pmin','узел_после_рег_заряд_аккумулятора']:
        p0[node_index[name]] = P_ATM
    p0[node_index['узел_после_рег_Pmin_питание_Р2']] = Pmin_abs

    # Начальная статика (delta=0), шина держит массу

        # Геометрия колеса: радиус влияет на абсолютные координаты (и может использоваться в визуализации/контакте).
    # Поддерживаем как общий радиус, так и раздельно перед/зад.
    wheel_radius_front = _pfloat("радиус_колеса_перед_м", _pfloat("радиус_колеса_м", 0.0))
    wheel_radius_rear  = _pfloat("радиус_колеса_зад_м",   _pfloat("радиус_колеса_м", 0.0))

    # Если радиус не задан, допускаем ввод диаметра (общего или раздельно).
    if wheel_radius_front <= 0.0:
        wheel_radius_front = 0.5 * _pfloat("диаметр_колеса_перед_м", _pfloat("диаметр_колеса_м", 0.0))
    if wheel_radius_rear <= 0.0:
        wheel_radius_rear = 0.5 * _pfloat("диаметр_колеса_зад_м", _pfloat("диаметр_колеса_м", 0.0))

    wheel_radius_vec = np.array([wheel_radius_front, wheel_radius_front, wheel_radius_rear, wheel_radius_rear], dtype=float)
    wheel_radius_vec = np.maximum(wheel_radius_vec, 0.0)

    # Статика (delta=0): принимаем общую высоту рамы и одинаковое zw0 по углам.
    # (Если перед/зад радиусы сильно отличаются, лучше задавать статическое положение через отдельный решатель.)
    wheel_radius_mean = float(np.mean(wheel_radius_vec))
    z_static = wheel_radius_mean - (m_body*g/4.0 + m_w*g) / k_tire
    z0 = z_static
    phi0 = 0.0
    th0 = 0.0
    zw0 = np.ones(4) * z_static
    z_dot0 = phi_dot0 = th_dot0 = 0.0
    zw_dot0 = np.zeros(4)


    # Преднатяг пружин (учёт стартового усилия от пневматики)
    def F_cyl_total_at_p(p_vec):
        F = []
        for cname in corner_order:
            p1c = p_vec[node_index[f'Ц1_{cname}_БП']]
            p1r = p_vec[node_index[f'Ц1_{cname}_ШП']]
            p2c = p_vec[node_index[f'Ц2_{cname}_БП']]
            p2r = p_vec[node_index[f'Ц2_{cname}_ШП']]
            F1 = (p1c - P_ATM) * A1_cap - (p1r - P_ATM) * A1_rod
            F2 = (p2c - P_ATM) * A2_cap - (p2r - P_ATM) * A2_rod
            F.append(F1 + F2)
        return np.array(F)

        F_cyl0 = F_cyl_total_at_p(p0)

    # Режим пружины:
    #  - 'DELTA': как в базовой версии (x = x0 + delta) — совместимость
    #  - 'C1'   : пружина коаксиальна Ц1, работает по ходу штока (x = x0 + (s0_C1 - s_C1))
    #  - 'C2'   : аналогично по Ц2
    spring_mode = _pstr('пружина_по_цилиндру', 'C1').strip().upper()
    if spring_mode not in ('DELTA', 'C1', 'C2'):
        spring_mode = 'C1'

    # Оценка ds/ddelta в статике (delta=0) для пересчёта осевых сил в вертикальные
    if mech_kin == 'legacy':
        ds_ddelta0_C1 = -np.ones(4)
        ds_ddelta0_C2 = -np.ones(4)
    else:
        # ds/dδ = dL/dδ = -(low_frac * dz)/L, где dz = top_z - low_frac*delta; при delta=0: dz=top_z, L=L0
        ds_ddelta0_C1 = -(low_frac_C1 * top_z_C1) / np.maximum(1e-9, L0_C1)
        ds_ddelta0_C2 = -(low_frac_C2 * top_z_C2) / np.maximum(1e-9, L0_C2)

    # Вертикальная составляющая цилиндров в статике (на раму) — через виртуальную работу
    F_cyl_vert0 = np.zeros(4)
    for i_c, cname in enumerate(corner_order):
        p1c = p0[node_index[f'Ц1_{cname}_БП']]
        p1r = p0[node_index[f'Ц1_{cname}_ШП']]
        p2c = p0[node_index[f'Ц2_{cname}_БП']]
        p2r = p0[node_index[f'Ц2_{cname}_ШП']]
        F1_ax = (p1c - P_ATM) * A1_cap - (p1r - P_ATM) * A1_rod
        F2_ax = (p2c - P_ATM) * A2_cap - (p2r - P_ATM) * A2_rod
        F_cyl_vert0[i_c] = (-F1_ax * ds_ddelta0_C1[i_c]) + (-F2_ax * ds_ddelta0_C2[i_c])

    # Пружина: предсжатие (x0) вместо постоянного смещения силы.
    # Таблица только для сжатия (x>=0, F>=0). В динамике x = max(0, x0 + ...) в выбранном режиме.
    L_free = float(params.get('пружина_длина_свободная_м', float(табл_пруж_ход_м[-1]) if len(табл_пруж_ход_м) else 0.30))
    L_free = max(0.0, L_free)

    # Требуемая вертикальная сила пружины в статике
    F_spr_static_target_vert = m_body*g/4.0 - float(np.mean(F_cyl_vert0))
    F_spr_static_target_vert = max(0.0, F_spr_static_target_vert)

    # Переводим целевую вертикальную силу в осевую силу пружины (если пружина по цилиндру)
    if spring_mode == 'DELTA':
        F_spr_static_target_ax = F_spr_static_target_vert
    elif spring_mode == 'C2':
        mr = float(np.mean(np.abs(ds_ddelta0_C2)))
        F_spr_static_target_ax = F_spr_static_target_vert / max(1e-6, mr)
    else:  # 'C1'
        mr = float(np.mean(np.abs(ds_ddelta0_C1)))
        F_spr_static_target_ax = F_spr_static_target_vert / max(1e-6, mr)

    F_tab_target = F_spr_static_target_ax / max(1e-9, масштаб_пружины)

    if len(табл_пруж_ход_м) >= 2:
        x0 = float(np.interp(
            F_tab_target,
            табл_пруж_сила_Н,
            табл_пруж_ход_м,
            left=float(табл_пруж_ход_м[0]),
            right=float(табл_пруж_ход_м[-1])
        ))
    else:
        x0 = 0.0

    x0 = float(min(max(0.0, x0), L_free))


    # Функция объёмов (дифференциальная)
    def volumes(z, phi, theta, zw, z_dot, phi_dot, theta_dot, zw_dot):
        V = V0_vec.copy()
        dV = np.zeros_like(V)

        z_body = z + math.sin(phi)*y_pos*math.cos(theta) - math.sin(theta)*x_pos
        delta = zw - z_body

        # -------------------------
        # Кинематика штока: C1/C2
        # -------------------------
        if mech_kin == 'legacy':
            # Как в базовой версии: s = s0 - delta, MR = 1
            s_raw_C1 = s0_C1 - delta
            s_raw_C2 = s0_C2 - delta
            dsraw_ddelta_C1 = -np.ones(4)
            dsraw_ddelta_C2 = -np.ones(4)
            # формально, только для диагностики
            L_C1 = L0_C1 + (s_raw_C1 - s0_C1)
            L_C2 = L0_C2 + (s_raw_C2 - s0_C2)
        else:
            # Упрощённая геометрия установки цилиндра в плоскости Y–Z (double-wishbone-like)
            dz_C1 = top_z_C1 - low_frac_C1 * delta
            dz_C2 = top_z_C2 - low_frac_C2 * delta

            L_C1 = np.sqrt(dy_C1**2 + dz_C1**2)
            L_C2 = np.sqrt(dy_C2**2 + dz_C2**2)

            # Калибровка: при delta=0 получаем s≈mid (s0) за счёт L0
            s_raw_C1 = s0_C1 + (L_C1 - L0_C1)
            s_raw_C2 = s0_C2 + (L_C2 - L0_C2)

            dsraw_ddelta_C1 = -(low_frac_C1 * dz_C1) / np.maximum(1e-9, L_C1)
            dsraw_ddelta_C2 = -(low_frac_C2 * dz_C2) / np.maximum(1e-9, L_C2)

        # Ограничение по ходу штока (0..stroke) с опцией гладкости для дифф. оптимизации
        if smooth_stroke:
            s_C1, ds_dsraw_C1 = smooth_clip_with_grad(s_raw_C1, 0.0, stroke_C1, smooth_eps_pos_m)
            s_C2, ds_dsraw_C2 = smooth_clip_with_grad(s_raw_C2, 0.0, stroke_C2, smooth_eps_pos_m)
        else:
            s_C1 = np.clip(s_raw_C1, 0.0, stroke_C1)
            s_C2 = np.clip(s_raw_C2, 0.0, stroke_C2)
            ds_dsraw_C1 = None
            ds_dsraw_C2 = None

        z_body_dot = (z_dot
                     + (math.cos(phi)*y_pos*math.cos(theta))*phi_dot
                     + (math.sin(phi)*y_pos*(-math.sin(theta)))*theta_dot
                     - (x_pos*math.cos(theta))*theta_dot)
        delta_dot = zw_dot - z_body_dot

        # Производные по времени и ds/dδ (motion ratio)
        s_raw_dot_C1 = dsraw_ddelta_C1 * delta_dot
        s_raw_dot_C2 = dsraw_ddelta_C2 * delta_dot

        if smooth_stroke:
            s_dot_C1 = ds_dsraw_C1 * s_raw_dot_C1
            s_dot_C2 = ds_dsraw_C2 * s_raw_dot_C2
            ds_ddelta_C1 = ds_dsraw_C1 * dsraw_ddelta_C1
            ds_ddelta_C2 = ds_dsraw_C2 * dsraw_ddelta_C2
        elif consistent_stroke_kinematics:
            gate_C1 = ((s_raw_C1 > 0.0) & (s_raw_C1 < stroke_C1)).astype(float)
            gate_C2 = ((s_raw_C2 > 0.0) & (s_raw_C2 < stroke_C2)).astype(float)
            s_dot_C1 = s_raw_dot_C1 * gate_C1
            s_dot_C2 = s_raw_dot_C2 * gate_C2
            ds_ddelta_C1 = dsraw_ddelta_C1 * gate_C1
            ds_ddelta_C2 = dsraw_ddelta_C2 * gate_C2
        else:
            s_dot_C1 = s_raw_dot_C1
            s_dot_C2 = s_raw_dot_C2
            ds_ddelta_C1 = dsraw_ddelta_C1
            ds_ddelta_C2 = dsraw_ddelta_C2

        # Для камер берём ход соответствующего цилиндра (C1 или C2)
        s_for_ch = np.where(chamber_cyl_id == 1, s_C1[chamber_corner], s_C2[chamber_corner])
        sdot_for_ch = np.where(chamber_cyl_id == 1, s_dot_C1[chamber_corner], s_dot_C2[chamber_corner])

        V[chamber_indices] = chamber_offset + chamber_sign*chamber_area*s_for_ch
        dV[chamber_indices] = chamber_sign*chamber_area*sdot_for_ch

        return (V, dV, delta,
                s_C1, s_dot_C1,
                s_C2, s_dot_C2,
                ds_ddelta_C1, ds_ddelta_C2,
                s_raw_C1, s_raw_C2,
                s_raw_dot_C1, s_raw_dot_C2,
                L_C1, L_C2)

    V_init, *_ = volumes(z0, phi0, th0, zw0, z_dot0, phi_dot0, th_dot0, zw_dot0)
    m0 = p0 * V_init / (R_AIR * T_AIR)
    m0[node_index['АТМ']] = P_ATM * V0_vec[node_index['АТМ']] / (R_AIR * T_AIR)

    # Состояние
    state0 = np.concatenate([
        np.array([z0, phi0, th0]),
        zw0,
        np.array([z_dot0, phi_dot0, th_dot0]),
        zw_dot0,
        m0
    ])


    # Поддержка suite/UI тестов: если передан 'тип' без функций — соберём ax/ay/road.
    if isinstance(test, dict) and ("тип" in test):
        try:
            need = any((k not in test) or (not callable(test.get(k, None))) for k in ("ax_func", "ay_func", "road_func"))
            if need:
                add = _compile_suite_test_inputs(test, params)
                if add:
                    test = dict(test)  # не мутируем исходный объект
                    test.update(add)
        except Exception:
            # Любая ошибка компиляции не должна валить симуляцию
            pass

    # Внешние воздействия
    ay_func = test.get('ay_func', lambda t: 0.0)
    ax_func = test.get('ax_func', lambda t: 0.0)
    road_func = test.get('road_func', lambda t: np.zeros(4))
    label_func = test.get('label_func', lambda t: 0)

    def compute_pressures(state):
        z, phi, theta = state[0], state[1], state[2]
        zw = state[3:7]
        z_dot, phi_dot, theta_dot = state[7], state[8], state[9]
        zw_dot = state[10:14]
        m = state[14:].copy()

        V, dV, delta, s_C1, s_dot_C1, s_C2, s_dot_C2, ds_ddelta_C1, ds_ddelta_C2, s_raw_C1, s_raw_C2, s_raw_dot_C1, s_raw_dot_C2, L_C1, L_C2 = volumes(z, phi, theta, zw, z_dot, phi_dot, theta_dot, zw_dot)

        # атмосфера как граничное условие + допускаем вакуум (p_abs может быть ниже P_ATM, но не ниже p_abs_min)
        p_abs_min = float(params.get('минимальное_абсолютное_давление_Па', 1000.0))

        # атмосфера (граничное условие)
        m[node_index['АТМ']] = P_ATM * V0_vec[node_index['АТМ']] / (R_AIR * T_AIR)

        if smooth_pressure_floor:
            V_safe = smooth_max(V, 1e-9, smooth_eps_vol_m3)
        else:
            V_safe = np.maximum(1e-9, V)

        # Жёстко обеспечиваем физичность: m >= p_abs_min*V/(R*T)  ⇔  p_abs >= p_abs_min
        m_floor = (p_abs_min * V_safe) / (R_AIR * T_AIR)
        if smooth_pressure_floor:
            m = m_floor + smooth_pos(m - m_floor, smooth_eps_mass_kg)
        else:
            m = np.maximum(m, m_floor)

        p = m * R_AIR * T_AIR / V_safe
        p[node_index['АТМ']] = P_ATM
        return p, V, dV, delta, s_C1, s_dot_C1, s_C2, s_dot_C2, ds_ddelta_C1, ds_ddelta_C2, s_raw_C1, s_raw_C2, s_raw_dot_C1, s_raw_dot_C2, L_C1, L_C2

    # Параметры сглаживания логики клапанов (для дифференцируемости)
    # Если smooth_valves=False — поведение полностью как раньше (жёсткие if).
    smooth_valves = bool(params.get('smooth_valves', smooth_dynamics))
    k_smooth_valves = float(params.get('k_smooth_valves', 80.0))  # чем больше, тем резче (ближе к step)

    def _gate01(x: float) -> float:
        """Гладкий аналог Heaviside(x): возвращает значение в [0;1]."""
        # 0.5*(1+tanh(.)) — численно устойчивее, чем exp для больших k*x
        return 0.5 * (1.0 + math.tanh(0.5 * k_smooth_valves * x))

    def compute_flows(p):
        mdots = np.zeros(E)
        for ei, e in enumerate(edges):
            pu = p[e.n1]
            pdn = p[e.n2]

            if e.kind == 'orifice':
                # Двусторонний дроссель (может менять направление)
                mdots[ei] = mdot_orifice_signed(pu, pdn, e.A, e.Cd)

            elif e.kind == 'check':
                if smooth_valves:
                    g = _gate01(pu - pdn - e.dp_crack)
                    mdots[ei] = g * mdot_orifice(pu, pdn, e.A, e.Cd)
                else:
                    mdots[ei] = mdot_orifice(pu, pdn, e.A, e.Cd) if pu > pdn + e.dp_crack else 0.0

            elif e.kind == 'reg_after':
                if smooth_valves:
                    # Открываем, если downstream ниже уставки, и есть перепад на открытие
                    g1 = _gate01(e.p_set - pdn)              # p_dn < p_set
                    g2 = _gate01(pu - pdn - e.dp_crack)      # pu > pdn + dp_crack
                    mdots[ei] = (g1 * g2) * mdot_orifice(pu, pdn, e.A, e.Cd)
                else:
                    if (p[e.n2] < e.p_set) and (pu > pdn + e.dp_crack):
                        mdots[ei] = mdot_orifice(pu, pdn, e.A, e.Cd)
                    else:
                        mdots[ei] = 0.0

            elif e.kind == 'relief':
                if smooth_valves:
                    # Открываем, если upstream выше уставки, и поток вообще возможен (pu>pdn)
                    g1 = _gate01(pu - e.p_set)
                    g2 = _gate01(pu - pdn)
                    mdots[ei] = (g1 * g2) * mdot_orifice(pu, pdn, e.A, e.Cd)
                else:
                    if (pu > e.p_set) and (pu > pdn):
                        mdots[ei] = mdot_orifice(pu, pdn, e.A, e.Cd)
                    else:
                        mdots[ei] = 0.0
        return mdots

    def rhs(state, t):
        """Правая часть ОДУ (без логирования!). Логирование делается снаружи,
        иначе при RK2 второй вызов rhs(mid, t+dt) перетирает значения в out[k]."""
        z, phi, theta = state[0], state[1], state[2]
        zw = state[3:7]
        z_dot, phi_dot, theta_dot = state[7], state[8], state[9]
        zw_dot = state[10:14]

        p, V, dV, delta, s_C1, s_dot_C1, s_C2, s_dot_C2, ds_ddelta_C1, ds_ddelta_C2, s_raw_C1, s_raw_C2, s_raw_dot_C1, s_raw_dot_C2, L_C1, L_C2 = compute_pressures(state)
        mdots = compute_flows(p)

        dm_dt = B @ mdots
        dm_dt[node_index['АТМ']] = 0.0

                # Силы подвески (пружина + пневмоцилиндры + упоры)
        # delta, s_C1/s_C2, s_raw_* и ds_ddelta_* получены из compute_pressures(state)

        # -------------------------
        # Пружина (односторонняя)
        # -------------------------
        if spring_mode == 'DELTA':
            x = x0 + delta
            if smooth_spring:
                x_comp = smooth_max(x, 0.0, smooth_eps_pos_m)
                x_comp = smooth_min(x_comp, L_free, smooth_eps_pos_m)
            else:
                x_comp = np.clip(x, 0.0, L_free)
            F_inc = np.interp(x_comp, табл_пруж_ход_м, табл_пруж_сила_Н)
            F_spr_ax = масштаб_пружины * F_inc
            F_spr_vert = F_spr_ax
        elif spring_mode == 'C2':
            x = x0 + (s0_C2 - s_C2)
            if smooth_spring:
                x_comp = smooth_max(x, 0.0, smooth_eps_pos_m)
                x_comp = smooth_min(x_comp, L_free, smooth_eps_pos_m)
            else:
                x_comp = np.clip(x, 0.0, L_free)
            F_inc = np.interp(x_comp, табл_пруж_ход_м, табл_пруж_сила_Н)
            F_spr_ax = масштаб_пружины * F_inc
            F_spr_vert = -F_spr_ax * ds_ddelta_C2
        else:  # 'C1'
            x = x0 + (s0_C1 - s_C1)
            if smooth_spring:
                x_comp = smooth_max(x, 0.0, smooth_eps_pos_m)
                x_comp = smooth_min(x_comp, L_free, smooth_eps_pos_m)
            else:
                x_comp = np.clip(x, 0.0, L_free)
            F_inc = np.interp(x_comp, табл_пруж_ход_м, табл_пруж_сила_Н)
            F_spr_ax = масштаб_пружины * F_inc
            F_spr_vert = -F_spr_ax * ds_ddelta_C1

        # -------------------------
        # Силы цилиндров (осевые -> вертикаль через виртуальную работу)
        # -------------------------
        F1_ax = np.zeros(4)
        F2_ax = np.zeros(4)
        for i_c, cname in enumerate(corner_order):
            p1c = p[node_index[f'Ц1_{cname}_БП']]
            p1r = p[node_index[f'Ц1_{cname}_ШП']]
            p2c = p[node_index[f'Ц2_{cname}_БП']]
            p2r = p[node_index[f'Ц2_{cname}_ШП']]
            F1_ax[i_c] = (p1c - P_ATM) * A1_cap - (p1r - P_ATM) * A1_rod
            F2_ax[i_c] = (p2c - P_ATM) * A2_cap - (p2r - P_ATM) * A2_rod

        F_cyl_vert = (-F1_ax * ds_ddelta_C1) + (-F2_ax * ds_ddelta_C2)

        F_susp = F_spr_vert + F_cyl_vert

        # -------------------------
        # Упоры по ходу штока (моделируем как "жёсткий" конец цилиндра)
        # Bump: s_raw < 0  => дополнительная положительная осевая сила
        # Rebound: s_raw > stroke => дополнительная отрицательная осевая сила
        # -------------------------
        k_stop = _pfloat('жёсткость_отбойника', 1.0e6)
        c_stop = _pfloat('демпфирование_отбойника', 5.0e3)

        def _stop_force_ax(s_raw, s_raw_dot, stroke):
            over_bump = -s_raw
            over_reb = s_raw - stroke
            vel_into_bump = -s_raw_dot
            vel_into_reb = s_raw_dot
            if smooth_contacts:
                bump_pos = smooth_pos(over_bump, smooth_eps_pos_m)
                reb_pos = smooth_pos(over_reb, smooth_eps_pos_m)
                gb = smooth_pos_grad(over_bump, smooth_eps_pos_m)
                gr = smooth_pos_grad(over_reb, smooth_eps_pos_m)
                vb = smooth_pos(vel_into_bump, smooth_eps_vel_mps)
                vr = smooth_pos(vel_into_reb, smooth_eps_vel_mps)
                return (k_stop*bump_pos + c_stop*vb*gb) - (k_stop*reb_pos + c_stop*vr*gr)
            else:
                F = np.zeros_like(s_raw, dtype=float)
                F += np.where(over_bump > 0.0, k_stop*over_bump + c_stop*np.maximum(vel_into_bump, 0.0), 0.0)
                F -= np.where(over_reb > 0.0, k_stop*over_reb + c_stop*np.maximum(vel_into_reb, 0.0), 0.0)
                return F

        F_stop_C1_ax = _stop_force_ax(s_raw_C1, s_raw_dot_C1, stroke_C1)
        F_stop_C2_ax = _stop_force_ax(s_raw_C2, s_raw_dot_C2, stroke_C2)

        F_stop_vert = (-F_stop_C1_ax * ds_ddelta_C1) + (-F_stop_C2_ax * ds_ddelta_C2)
        F_susp = F_susp + F_stop_vert

        # -------------------------
        # Моменты от сил подвески + инерционные моменты от ax/ay через высоту ЦМ
        # -------------------------
        M_roll = np.sum(F_susp * y_pos) + m_body*ay_func(t)*h_cg
        M_pitch = -np.sum(F_susp * x_pos) + m_body*ax_func(t)*h_cg

        z_ddot = (np.sum(F_susp) - m_body*g) / m_body
        phi_ddot = M_roll / I_roll
        theta_ddot = M_pitch / I_pitch
# Колёса и контакт (односторонний)
        z_road = road_func(t)
        pen = (z_road - zw + wheel_radius_vec)
        pen_dot = -zw_dot
        if smooth_contacts:
            pen_pos = smooth_pos(pen, smooth_eps_pos_m)
            g_contact = smooth_pos_grad(pen, smooth_eps_pos_m)
            pen_dot_pos = smooth_pos(pen_dot, smooth_eps_vel_mps)
            F_tire = k_tire*pen_pos + c_tire*pen_dot_pos*g_contact
        else:
            F_tire = np.where(pen > 0.0, k_tire*pen + c_tire*np.maximum(pen_dot, 0.0), 0.0)
        zw_ddot = (F_tire - F_susp - m_w*g) / m_w

        dst = np.zeros_like(state)
        dst[0] = z_dot
        dst[1] = phi_dot
        dst[2] = theta_dot
        dst[3:7] = zw_dot
        dst[7] = z_ddot
        dst[8] = phi_ddot
        dst[9] = theta_ddot
        dst[10:14] = zw_ddot
        dst[14:] = dm_dt
        return dst
    # -------------------------
    # Интегрирование (RK2)
    # -------------------------
    # Важно: ось времени должна соответствовать dt интегрирования.
    try:
        from .time_grid import build_time_grid
    except Exception:
        from time_grid import build_time_grid
    time = build_time_grid(dt=float(dt), t_end=float(t_end), t0=0.0, mode="floor")
    n_steps = len(time)

    drossel_edges = [ei for ei, e in enumerate(edges) if e.group == 'дроссель']
    drossel_names = [edges[ei].name for ei in drossel_edges]
    mdot_drossel = np.zeros((n_steps, len(drossel_edges)))
    E_drossel = np.zeros(len(drossel_edges))

    # Энерго‑аудит по всем сопротивлениям (дроссели/выхлоп/клапаны/регуляторы)
    # Мощность потерь аппрокс.: N_потерь = Δp * Q_up, где Q_up = |ṁ| / ρ_up.
    # Для двунаправленного дросселя upstream определяется знаком ṁ.
    diss_edges = [ei for ei, e in enumerate(edges) if e.kind in ('orifice','check','reg_after','relief')]
    diss_names = [edges[ei].name for ei in diss_edges]
    diss_groups = [(edges[ei].group or '') for ei in diss_edges]
    diss_kinds = [edges[ei].kind for ei in diss_edges]
    diss_camozzi = [edges[ei].camozzi_код for ei in diss_edges]
    E_diss = np.zeros(len(diss_edges))
    M_diss = np.zeros(len(diss_edges))   # интеграл |ṁ| dt (кг)
    M_to_atm = 0.0
    M_from_atm = 0.0
    idx_atm = node_index['АТМ']
    P_N = float(params.get('P_N_Па', P_N_DEFAULT))
    T_N = float(params.get('T_N_К', T_N_DEFAULT))
    rho_N = P_N/(R_AIR*T_N)

    # Полные записи для UI (по требованию): давления во всех узлах + расходы во всех рёбрах
    p_full = np.zeros((n_steps, N), dtype=float) if record_full else None
    mdot_full = np.zeros((n_steps, E), dtype=float) if record_full else None
    open_full = np.zeros((n_steps, E), dtype=np.int8) if record_full else None

    out = {
        'время_с': time,
        'перемещение_рамы_z_м': np.zeros(n_steps),
        'крен_phi_рад': np.zeros(n_steps),
        'тангаж_theta_рад': np.zeros(n_steps),

        # Внешние воздействия (для анализа инерция/дорога)
        'ускорение_продольное_ax_м_с2': np.zeros(n_steps),
        'ускорение_поперечное_ay_м_с2': np.zeros(n_steps),
        'сегмент_id': np.zeros(n_steps, dtype=int),

        # Колёса
        'перемещение_колеса_ЛП_м': np.zeros(n_steps),
        'перемещение_колеса_ПП_м': np.zeros(n_steps),
        'перемещение_колеса_ЛЗ_м': np.zeros(n_steps),
        'перемещение_колеса_ПЗ_м': np.zeros(n_steps),

        # Штоки цилиндров (положение 0..ход_штока) и скорость (для KPI по упорам/скоростям)
        # В данной кинематической схеме оба цилиндра на углу (Ц1 и Ц2) имеют одинаковый ход штока.
        'положение_штока_ЛП_м': np.zeros(n_steps),
        'положение_штока_ПП_м': np.zeros(n_steps),
        'положение_штока_ЛЗ_м': np.zeros(n_steps),
        'положение_штока_ПЗ_м': np.zeros(n_steps),
        'скорость_штока_ЛП_м_с': np.zeros(n_steps),
        'скорость_штока_ПП_м_с': np.zeros(n_steps),
        'скорость_штока_ЛЗ_м_с': np.zeros(n_steps),
        'скорость_штока_ПЗ_м_с': np.zeros(n_steps),
        'положение_штока_Ц2_ЛП_м': np.zeros(n_steps),
        'положение_штока_Ц2_ПП_м': np.zeros(n_steps),
        'положение_штока_Ц2_ЛЗ_м': np.zeros(n_steps),
        'положение_штока_Ц2_ПЗ_м': np.zeros(n_steps),
        'скорость_штока_Ц2_ЛП_м_с': np.zeros(n_steps),
        'скорость_штока_Ц2_ПП_м_с': np.zeros(n_steps),
        'скорость_штока_Ц2_ЛЗ_м_с': np.zeros(n_steps),
        'скорость_штока_Ц2_ПЗ_м_с': np.zeros(n_steps),

        'motion_ratio_Ц1_ЛП': np.zeros(n_steps),
        'motion_ratio_Ц1_ПП': np.zeros(n_steps),
        'motion_ratio_Ц1_ЛЗ': np.zeros(n_steps),
        'motion_ratio_Ц1_ПЗ': np.zeros(n_steps),
        'motion_ratio_Ц2_ЛП': np.zeros(n_steps),
        'motion_ratio_Ц2_ПП': np.zeros(n_steps),
        'motion_ratio_Ц2_ЛЗ': np.zeros(n_steps),
        'motion_ratio_Ц2_ПЗ': np.zeros(n_steps),

        'длина_цилиндра_Ц1_ЛП_м': np.zeros(n_steps),
        'длина_цилиндра_Ц1_ПП_м': np.zeros(n_steps),
        'длина_цилиндра_Ц1_ЛЗ_м': np.zeros(n_steps),
        'длина_цилиндра_Ц1_ПЗ_м': np.zeros(n_steps),
        'длина_цилиндра_Ц2_ЛП_м': np.zeros(n_steps),
        'длина_цилиндра_Ц2_ПП_м': np.zeros(n_steps),
        'длина_цилиндра_Ц2_ЛЗ_м': np.zeros(n_steps),
        'длина_цилиндра_Ц2_ПЗ_м': np.zeros(n_steps),
        'нормальная_сила_шины_ЛП_Н': np.zeros(n_steps),
        'нормальная_сила_шины_ПП_Н': np.zeros(n_steps),
        'нормальная_сила_шины_ЛЗ_Н': np.zeros(n_steps),
        'нормальная_сила_шины_ПЗ_Н': np.zeros(n_steps),
        'колесо_в_воздухе_ЛП': np.zeros(n_steps, dtype=int),
        'колесо_в_воздухе_ПП': np.zeros(n_steps, dtype=int),
        'колесо_в_воздухе_ЛЗ': np.zeros(n_steps, dtype=int),
        'колесо_в_воздухе_ПЗ': np.zeros(n_steps, dtype=int),

        # Дорога под каждым колесом
        'дорога_ЛП_м': np.zeros(n_steps),
        'дорога_ПП_м': np.zeros(n_steps),
        'дорога_ЛЗ_м': np.zeros(n_steps),
        'дорога_ПЗ_м': np.zeros(n_steps),

        # Давления (ключевые)
        'давление_ресивер1_Па': np.zeros(n_steps),
        'давление_ресивер2_Па': np.zeros(n_steps),
        'давление_ресивер3_Па': np.zeros(n_steps),
        'давление_аккумулятор_Па': np.zeros(n_steps),

        # Доп. наблюдаемость (P0): скорости/ускорения рамы и углов
        # Ускорения вычисляем после интегрирования через численную производную (gradient).
        'скорость_рамы_z_м_с': np.zeros(n_steps),
        'ускорение_рамы_z_м_с2': np.zeros(n_steps),
        'скорость_крен_phi_рад_с': np.zeros(n_steps),
        'ускорение_крен_phi_рад_с2': np.zeros(n_steps),
        'скорость_тангаж_theta_рад_с': np.zeros(n_steps),
        'ускорение_тангаж_theta_рад_с2': np.zeros(n_steps),

        # Рама по углам (в точках колёс): z/v/a (P0)
        'рама_угол_ЛП_z_м': np.zeros(n_steps),
        'рама_угол_ПП_z_м': np.zeros(n_steps),
        'рама_угол_ЛЗ_z_м': np.zeros(n_steps),
        'рама_угол_ПЗ_z_м': np.zeros(n_steps),
        'рама_угол_ЛП_v_м_с': np.zeros(n_steps),
        'рама_угол_ПП_v_м_с': np.zeros(n_steps),
        'рама_угол_ЛЗ_v_м_с': np.zeros(n_steps),
        'рама_угол_ПЗ_v_м_с': np.zeros(n_steps),
        'рама_угол_ЛП_a_м_с2': np.zeros(n_steps),
        'рама_угол_ПП_a_м_с2': np.zeros(n_steps),
        'рама_угол_ЛЗ_a_м_с2': np.zeros(n_steps),
        'рама_угол_ПЗ_a_м_с2': np.zeros(n_steps),

        # Колёса: скорости/ускорения (для KPI и проверки)
        'скорость_колеса_ЛП_м_с': np.zeros(n_steps),
        'скорость_колеса_ПП_м_с': np.zeros(n_steps),
        'скорость_колеса_ЛЗ_м_с': np.zeros(n_steps),
        'скорость_колеса_ПЗ_м_с': np.zeros(n_steps),
        'ускорение_колеса_ЛП_м_с2': np.zeros(n_steps),
        'ускорение_колеса_ПП_м_с2': np.zeros(n_steps),
        'ускорение_колеса_ЛЗ_м_с2': np.zeros(n_steps),
        'ускорение_колеса_ПЗ_м_с2': np.zeros(n_steps),

        # Относительные перемещения колеса
        'колесо_относительно_рамы_ЛП_м': np.zeros(n_steps),
        'колесо_относительно_рамы_ПП_м': np.zeros(n_steps),
        'колесо_относительно_рамы_ЛЗ_м': np.zeros(n_steps),
        'колесо_относительно_рамы_ПЗ_м': np.zeros(n_steps),
        'колесо_относительно_дороги_ЛП_м': np.zeros(n_steps),
        'колесо_относительно_дороги_ПП_м': np.zeros(n_steps),
        'колесо_относительно_дороги_ЛЗ_м': np.zeros(n_steps),
        'колесо_относительно_дороги_ПЗ_м': np.zeros(n_steps),

        # World-frame (минимум): vx и x вдоль дороги + yaw (оценка из ay и vx)
        'скорость_vx_м_с': np.zeros(n_steps),
        'путь_x_м': np.zeros(n_steps),
        'yaw_rate_рад_с': np.zeros(n_steps),
        'yaw_рад': np.zeros(n_steps),
        'радиус_поворота_м': np.zeros(n_steps),
    }

    state = state0.copy()
    for k, t in enumerate(time):
        out['перемещение_рамы_z_м'][k] = state[0]
        out['крен_phi_рад'][k] = state[1]
        out['тангаж_theta_рад'][k] = state[2]

        # Скорости рамы/углов (ускорения будут рассчитаны после интегрирования)
        out['скорость_рамы_z_м_с'][k] = state[7]
        out['скорость_крен_phi_рад_с'][k] = state[8]
        out['скорость_тангаж_theta_рад_с'][k] = state[9]

        # Рама в точках колёс (геометрия на основе x_pos/y_pos)
        z, phi, theta = state[0], state[1], state[2]
        z_dot, phi_dot, theta_dot = state[7], state[8], state[9]
        z_body = z + math.sin(phi)*y_pos*math.cos(theta) - math.sin(theta)*x_pos
        z_body_dot = (z_dot
                      + (math.cos(phi)*y_pos*math.cos(theta))*phi_dot
                      + (math.sin(phi)*y_pos*(-math.sin(theta)))*theta_dot
                      - (x_pos*math.cos(theta))*theta_dot)

        out['рама_угол_ЛП_z_м'][k] = float(z_body[0])
        out['рама_угол_ПП_z_м'][k] = float(z_body[1])
        out['рама_угол_ЛЗ_z_м'][k] = float(z_body[2])
        out['рама_угол_ПЗ_z_м'][k] = float(z_body[3])

        out['рама_угол_ЛП_v_м_с'][k] = float(z_body_dot[0])
        out['рама_угол_ПП_v_м_с'][k] = float(z_body_dot[1])
        out['рама_угол_ЛЗ_v_м_с'][k] = float(z_body_dot[2])
        out['рама_угол_ПЗ_v_м_с'][k] = float(z_body_dot[3])

        # Логируем внешние воздействия (для разделения инерции и дороги)
        out['ускорение_продольное_ax_м_с2'][k] = float(ax_func(t))
        out['ускорение_поперечное_ay_м_с2'][k] = float(ay_func(t))
        out['сегмент_id'][k] = int(label_func(t))

        # Опрокидывание: аварийная остановка (только если совсем вышли за разумные углы)
        # А «запас до опрокидывания» считаем в KPI отдельной непрерывной метрикой.
        if (abs(state[1]) > phi_abort) or (abs(state[2]) > theta_abort):
            raise RolloverException(f"Аварийная остановка (углы): phi={state[1]:.3f} рад, theta={state[2]:.3f} рад")

        out['перемещение_колеса_ЛП_м'][k] = state[3]
        out['перемещение_колеса_ПП_м'][k] = state[4]
        out['перемещение_колеса_ЛЗ_м'][k] = state[5]
        out['перемещение_колеса_ПЗ_м'][k] = state[6]

        # Скорости колёс (ускорения будут рассчитаны после интегрирования)
        out['скорость_колеса_ЛП_м_с'][k] = state[10]
        out['скорость_колеса_ПП_м_с'][k] = state[11]
        out['скорость_колеса_ЛЗ_м_с'][k] = state[12]
        out['скорость_колеса_ПЗ_м_с'][k] = state[13]

        # Колёса относительно рамы (P0): z_wheel - z_body
        out['колесо_относительно_рамы_ЛП_м'][k] = float(state[3] - z_body[0])
        out['колесо_относительно_рамы_ПП_м'][k] = float(state[4] - z_body[1])
        out['колесо_относительно_рамы_ЛЗ_м'][k] = float(state[5] - z_body[2])
        out['колесо_относительно_рамы_ПЗ_м'][k] = float(state[6] - z_body[3])

        p, V, dV, delta, s_C1, s_dot_C1, s_C2, s_dot_C2, ds_ddelta_C1, ds_ddelta_C2, s_raw_C1, s_raw_C2, s_raw_dot_C1, s_raw_dot_C2, L_C1, L_C2 = compute_pressures(state)

        # Лог штоков (положение/скорость) — нужны для KPI по упорам/скоростям
        # Для обратной совместимости 'положение_штока_*' считаем по Ц1.
        out['положение_штока_ЛП_м'][k] = float(s_C1[0])
        out['положение_штока_ПП_м'][k] = float(s_C1[1])
        out['положение_штока_ЛЗ_м'][k] = float(s_C1[2])
        out['положение_штока_ПЗ_м'][k] = float(s_C1[3])
        out['скорость_штока_ЛП_м_с'][k] = float(s_dot_C1[0])
        out['скорость_штока_ПП_м_с'][k] = float(s_dot_C1[1])
        out['скорость_штока_ЛЗ_м_с'][k] = float(s_dot_C1[2])
        out['скорость_штока_ПЗ_м_с'][k] = float(s_dot_C1[3])

        # Ц2 отдельно
        out['положение_штока_Ц2_ЛП_м'][k] = float(s_C2[0])
        out['положение_штока_Ц2_ПП_м'][k] = float(s_C2[1])
        out['положение_штока_Ц2_ЛЗ_м'][k] = float(s_C2[2])
        out['положение_штока_Ц2_ПЗ_м'][k] = float(s_C2[3])
        out['скорость_штока_Ц2_ЛП_м_с'][k] = float(s_dot_C2[0])
        out['скорость_штока_Ц2_ПП_м_с'][k] = float(s_dot_C2[1])
        out['скорость_штока_Ц2_ЛЗ_м_с'][k] = float(s_dot_C2[2])
        out['скорость_штока_Ц2_ПЗ_м_с'][k] = float(s_dot_C2[3])

        # Motion ratio (|ds/dδ|) и длины цилиндров для диагностики кинематики
        mr1 = np.abs(ds_ddelta_C1)
        mr2 = np.abs(ds_ddelta_C2)
        out['motion_ratio_Ц1_ЛП'][k] = float(mr1[0])
        out['motion_ratio_Ц1_ПП'][k] = float(mr1[1])
        out['motion_ratio_Ц1_ЛЗ'][k] = float(mr1[2])
        out['motion_ratio_Ц1_ПЗ'][k] = float(mr1[3])
        out['motion_ratio_Ц2_ЛП'][k] = float(mr2[0])
        out['motion_ratio_Ц2_ПП'][k] = float(mr2[1])
        out['motion_ratio_Ц2_ЛЗ'][k] = float(mr2[2])
        out['motion_ratio_Ц2_ПЗ'][k] = float(mr2[3])

        out['длина_цилиндра_Ц1_ЛП_м'][k] = float(L_C1[0])
        out['длина_цилиндра_Ц1_ПП_м'][k] = float(L_C1[1])
        out['длина_цилиндра_Ц1_ЛЗ_м'][k] = float(L_C1[2])
        out['длина_цилиндра_Ц1_ПЗ_м'][k] = float(L_C1[3])
        out['длина_цилиндра_Ц2_ЛП_м'][k] = float(L_C2[0])
        out['длина_цилиндра_Ц2_ПП_м'][k] = float(L_C2[1])
        out['длина_цилиндра_Ц2_ЛЗ_м'][k] = float(L_C2[2])
        out['длина_цилиндра_Ц2_ПЗ_м'][k] = float(L_C2[3])

        # Дорога и контактные реакции шин (для контроля отрыва)
        z_road = road_func(t)
        zw = state[3:7]
        zw_dot = state[10:14]
        pen = (z_road - zw + wheel_radius_vec)
        pen_dot = -zw_dot
        if smooth_contacts:
            pen_pos = smooth_pos(pen, smooth_eps_pos_m)
            g_contact = smooth_pos_grad(pen, smooth_eps_pos_m)
            pen_dot_pos = smooth_pos(pen_dot, smooth_eps_vel_mps)
            F_tire = k_tire*pen_pos + c_tire*pen_dot_pos*g_contact
        else:
            F_tire = np.where(pen > 0.0, k_tire*pen + c_tire*np.maximum(pen_dot, 0.0), 0.0)
        out['дорога_ЛП_м'][k] = z_road[0]
        out['дорога_ПП_м'][k] = z_road[1]
        out['дорога_ЛЗ_м'][k] = z_road[2]
        out['дорога_ПЗ_м'][k] = z_road[3]

        # Колёса относительно дороги (P0): высота центра колеса над профилем дороги
        out['колесо_относительно_дороги_ЛП_м'][k] = float(zw[0] - z_road[0])
        out['колесо_относительно_дороги_ПП_м'][k] = float(zw[1] - z_road[1])
        out['колесо_относительно_дороги_ЛЗ_м'][k] = float(zw[2] - z_road[2])
        out['колесо_относительно_дороги_ПЗ_м'][k] = float(zw[3] - z_road[3])

        out['нормальная_сила_шины_ЛП_Н'][k] = F_tire[0]
        out['нормальная_сила_шины_ПП_Н'][k] = F_tire[1]
        out['нормальная_сила_шины_ЛЗ_Н'][k] = F_tire[2]
        out['нормальная_сила_шины_ПЗ_Н'][k] = F_tire[3]

        out['колесо_в_воздухе_ЛП'][k] = int(F_tire[0] <= 1.0)
        out['колесо_в_воздухе_ПП'][k] = int(F_tire[1] <= 1.0)
        out['колесо_в_воздухе_ЛЗ'][k] = int(F_tire[2] <= 1.0)
        out['колесо_в_воздухе_ПЗ'][k] = int(F_tire[3] <= 1.0)
        out['давление_ресивер1_Па'][k] = p[node_index['Ресивер1']]
        out['давление_ресивер2_Па'][k] = p[node_index['Ресивер2']]
        out['давление_ресивер3_Па'][k] = p[node_index['Ресивер3']]
        out['давление_аккумулятор_Па'][k] = p[node_index['Аккумулятор']]

        mdots = compute_flows(p)

        if record_full:
            p_full[k, :] = p
            mdot_full[k, :] = mdots
            # Флаг открытия (упрощённо): 1 если элемент в «открытом» режиме по условию
            for ei, e in enumerate(edges):
                if e.kind == 'check':
                    open_full[k, ei] = 1 if (p[e.n1] > p[e.n2] + e.dp_crack) else 0
                elif e.kind == 'relief':
                    open_full[k, ei] = 1 if (p[e.n1] > e.p_set and p[e.n1] > p[e.n2]) else 0
                elif e.kind == 'reg_after':
                    open_full[k, ei] = 1 if (p[e.n2] < e.p_set and p[e.n1] > p[e.n2] + e.dp_crack) else 0
                else:
                    open_full[k, ei] = 0
        for j, ei in enumerate(drossel_edges):
            md = mdots[ei]
            mdot_drossel[k, j] = md

            # upstream по направлению фактического потока (важно для двунаправленного дросселя)
            e = edges[ei]
            if md >= 0.0:
                up = e.n1
                dn = e.n2
            else:
                up = e.n2
                dn = e.n1

            pu = p[up]
            pdn = p[dn]
            dp_pos = max(0.0, pu - pdn)
            rho_up = max(1e-3, pu / (R_AIR * T_AIR))
            Q_up = abs(md) / rho_up

            E_drossel[j] += dp_pos * Q_up * dt

        # Энерго‑аудит по всем сопротивлениям
        for j, ei in enumerate(diss_edges):
            md = mdots[ei]
            if md == 0.0:
                continue
            e = edges[ei]
            # направление фактического потока
            if md >= 0.0:
                up = e.n1
                dn = e.n2
            else:
                up = e.n2
                dn = e.n1
            pu = p[up]
            pdn = p[dn]
            dp_pos = max(0.0, pu - pdn)
            rho_up = max(1e-3, pu/(R_AIR*T_AIR))
            Q_up = abs(md)/rho_up
            E_diss[j] += dp_pos * Q_up * dt
            M_diss[j] += abs(md) * dt
            if dn == idx_atm:
                M_to_atm += abs(md) * dt
            if up == idx_atm:
                M_from_atm += abs(md) * dt

        if k < n_steps - 1:
            k1vec = rhs(state, t)
            mid = state + dt*k1vec
            k2vec = rhs(mid, t+dt)
            state = state + 0.5*dt*(k1vec + k2vec)

            # Проекция масс: не даём уйти в отрицательные массы и удерживаем p_abs >= p_abs_min (допускаем вакуум)
            p_abs_min = float(params.get('минимальное_абсолютное_давление_Па', 1000.0))
            z_, phi_, theta_ = state[0], state[1], state[2]
            zw_ = state[3:7]
            z_dot_, phi_dot_, theta_dot_ = state[7], state[8], state[9]
            zw_dot_ = state[10:14]
            V_tmp = volumes(z_, phi_, theta_, zw_, z_dot_, phi_dot_, theta_dot_, zw_dot_)[0]
            if smooth_pressure_floor:
                V_safe = smooth_max(V_tmp, 1e-9, smooth_eps_vol_m3)
            else:
                V_safe = np.maximum(1e-9, V_tmp)
            m_floor = (p_abs_min * V_safe) / (R_AIR * T_AIR)

            m_state = state[14:]
            if smooth_pressure_floor:
                m_state = m_floor + smooth_pos(m_state - m_floor, smooth_eps_mass_kg)
            else:
                m_state = np.maximum(m_state, m_floor)

            # атмосфера фиксирована
            m_state[node_index['АТМ']] = P_ATM * V0_vec[node_index['АТМ']] / (R_AIR * T_AIR)

            state[14:] = m_state

    # Post-processing: derive accelerations and world-frame kinematics.
    # Важно: это не «симуляция ради анимации», а производные от результатов расчёта.
    try:
        dt_ = float(dt)
        if dt_ > 0.0:
            out['ускорение_рамы_z_м_с2'][:] = np.gradient(out['скорость_рамы_z_м_с'], dt_)
            out['ускорение_крен_phi_рад_с2'][:] = np.gradient(out['скорость_крен_phi_рад_с'], dt_)
            out['ускорение_тангаж_theta_рад_с2'][:] = np.gradient(out['скорость_тангаж_theta_рад_с'], dt_)

            out['рама_угол_ЛП_a_м_с2'][:] = np.gradient(out['рама_угол_ЛП_v_м_с'], dt_)
            out['рама_угол_ПП_a_м_с2'][:] = np.gradient(out['рама_угол_ПП_v_м_с'], dt_)
            out['рама_угол_ЛЗ_a_м_с2'][:] = np.gradient(out['рама_угол_ЛЗ_v_м_с'], dt_)
            out['рама_угол_ПЗ_a_м_с2'][:] = np.gradient(out['рама_угол_ПЗ_v_м_с'], dt_)

            out['ускорение_колеса_ЛП_м_с2'][:] = np.gradient(out['скорость_колеса_ЛП_м_с'], dt_)
            out['ускорение_колеса_ПП_м_с2'][:] = np.gradient(out['скорость_колеса_ПП_м_с'], dt_)
            out['ускорение_колеса_ЛЗ_м_с2'][:] = np.gradient(out['скорость_колеса_ЛЗ_м_с'], dt_)
            out['ускорение_колеса_ПЗ_м_с2'][:] = np.gradient(out['скорость_колеса_ПЗ_м_с'], dt_)
    except Exception:
        pass

    # World-frame (минимум): интегрируем ax -> vx -> x, оцениваем yaw по ay и vx
    # (точно будет заменено на полноценную world-model в EPIC-WORLD).
    try:
        dt_ = float(dt)        # v0: ABSOLUTE LAW — единственный канонический ключ скорости: vx0_м_с
        v0 = None
        if test.get('vx0_м_с', None) is not None:
            try:
                v0 = float(test['vx0_м_с'])
            except Exception:
                v0 = None
        if v0 is None and params.get('vx0_м_с', None) is not None:
            try:
                v0 = float(params['vx0_м_с'])
            except Exception:
                v0 = None
        if v0 is None:
            v0 = 0.0
        vx = out['скорость_vx_м_с']
        xx = out['путь_x_м']
        ax = out['ускорение_продольное_ax_м_с2']
        n_ = int(len(vx))
        if n_ > 0:
            vx[0] = v0
            xx[0] = 0.0
            for i in range(1, n_):
                vx[i] = vx[i-1] + 0.5*(ax[i-1] + ax[i]) * dt_
                xx[i] = xx[i-1] + 0.5*(vx[i-1] + vx[i]) * dt_

        ay = out['ускорение_поперечное_ay_м_с2']
        R = out['радиус_поворота_м']
        yaw_rate = out['yaw_rate_рад_с']
        yaw = out['yaw_рад']
        eps = 1e-6
        for i in range(n_):
            if abs(ay[i]) > 1e-9 and abs(vx[i]) > eps:
                R[i] = (vx[i]*vx[i]) / ay[i]
                yaw_rate[i] = ay[i] / vx[i]
            else:
                R[i] = float('inf')
                yaw_rate[i] = 0.0
        if n_ > 0:
            yaw[0] = 0.0
            for i in range(1, n_):
                yaw[i] = yaw[i-1] + 0.5*(yaw_rate[i-1] + yaw_rate[i]) * dt_
    except Exception:
        pass

    df_main = pd.DataFrame(out)
    df_drossel = pd.DataFrame(mdot_drossel, columns=drossel_names)
    df_drossel.insert(0, 'время_с', time)
    df_energy = pd.DataFrame({
        'дроссель': drossel_names,
        'энергия_рассеяна_Дж': E_drossel
    })

    # Полный энерго‑аудит по всем сопротивлениям
    Vn_l = (M_diss / rho_N) * 1000.0  # Нормальные литры (Нл), интеграл |ṁ| dt / ρ_N
    df_energy_edges = pd.DataFrame({
        'элемент': diss_names,
        'тип_элемента': diss_kinds,
        'группа': [g if g else 'прочее' for g in diss_groups],
        'Camozzi_код': diss_camozzi,
        'энергия_Дж': E_diss,
        'объём_Нл_абс': Vn_l,
    })
    E_total = float(df_energy_edges['энергия_Дж'].sum())
    if E_total > 0.0:
        df_energy_edges['доля_энергии'] = df_energy_edges['энергия_Дж'] / E_total
    else:
        df_energy_edges['доля_энергии'] = 0.0

    df_energy_groups = df_energy_edges.groupby('группа', as_index=False)['энергия_Дж'].sum()
    if E_total > 0.0:
        df_energy_groups['доля_энергии'] = df_energy_groups['энергия_Дж'] / E_total
    else:
        df_energy_groups['доля_энергии'] = 0.0

    df_atm = pd.DataFrame([{
        'масса_в_атмосферу_кг': float(M_to_atm),
        'масса_из_атмосферы_кг': float(M_from_atm),
        'баланс_массы_кг': float(M_from_atm - M_to_atm)
    }])
    if record_full:
        df_p = pd.DataFrame(p_full, columns=[n.name for n in nodes])
        df_p.insert(0, 'время_с', time)
        df_mdot = pd.DataFrame(mdot_full, columns=[e.name for e in edges])
        df_mdot.insert(0, 'время_с', time)
        df_open = pd.DataFrame(open_full, columns=[e.name for e in edges])
        df_open.insert(0, 'время_с', time)
        out = (df_main, df_drossel, df_energy, nodes, edges, df_energy_edges, df_energy_groups, df_atm, df_p, df_mdot, df_open)
        if len(out) != 11:
            raise AssertionError(f'record_full output contract: expected 11 items, got {len(out)}')
        return out
    out = (df_main, df_drossel, df_energy, nodes, edges, df_energy_edges, df_energy_groups, df_atm)
    if len(out) != 8:
        raise AssertionError(f'output contract: expected 8 items, got {len(out)}')
    return out

def run_default_and_export_excel(output_path: str = 'результаты_полная_тесты_v3_camozzi_пружины.xlsx'):
    # Параметры (можно оптимизировать)
    params = {
        # Уставки адаптивности (ресивер 3) и питание Р2 из аккумулятора
        'давление_Pmin_питание_Ресивер2': P_ATM + 2e5,
        'давление_Pmin_сброс': P_ATM + 4.5e5,
        'давление_Pmid_сброс': P_ATM + 6.8e5,
        'давление_Pmax_предохран': P_ATM + 8e5,
        'начальное_давление_аккумулятора': P_ATM + 6e5,

        # Открытия дросселей SCO (0..1) = доля от максимального прохода по d_max выбранной модели
        'открытие_дросселя_Ц2_CAP_в_ROD': 0.35,
        'открытие_дросселя_Ц2_ROD_в_CAP': 0.35,
        'открытие_дросселя_выхлоп_Pmin': 0.08,
        'открытие_дросселя_выхлоп_Pmid': 0.18,
        'открытие_дросселя_выхлоп_Pmax': 0.70,

        # Нелинейная пружина: табличная добавочная сила относительно точки "середина хода"
        'пружина_таблица_ход_мм': [-125, -80, -40, -20, 0, 20, 50, 80, 125],
        'пружина_таблица_сила_Н': [-1200, -900, -500, -200, 0, 400, 1200, 2200, 4000],
        'пружина_масштаб': 1.0,
    }

    tests = {
        'инерция_крен_ay_step': {
            'ay_func': lambda t: 3.0 if t > 0.5 else 0.0,
            'road_func': lambda t: np.zeros(4),
            'описание': 'Ступень по боковому ускорению ay=3 м/с^2 после 0.5 с (имитация поворота).'
        },
        'инерция_тангаж_ax_step': {
            'ax_func': lambda t: 3.0 if t > 0.5 else 0.0,
            'road_func': lambda t: np.zeros(4),
            'описание': 'Ступень по продольному ускорению ax=3 м/с^2 после 0.5 с (торможение/разгон).'
        },
        'дорога_синфаза_sine_20мм_2Гц': {
            'road_func': lambda t: 0.02*np.sin(2*np.pi*2*t)*np.ones(4),
            'описание': 'Синфазная синусоида дороги 20 мм, 2 Гц, все колёса одинаково.'
        },
        'дорога_разнофаза_left_right_sine_20мм_2Гц': {
            'road_func': lambda t: 0.02*np.sin(2*np.pi*2*t)*np.array([1,-1,1,-1]),
            'описание': 'Разнофазная синусоида: левые +, правые - (креновое возбуждение).'
        },
        'дорога_диагональ_step_30мм': {
            'road_func': lambda t: (np.array([0.03,0.0,0.0,0.03]) if (1.0 < t < 1.3) else np.zeros(4)),
            'описание': 'Диагональный бугор: ЛП и ПЗ +30 мм на 0.3 с.'
        }
    }

    idx_atm = node_index['АТМ']
    P_N = float(params.get('P_N_Па', P_N_DEFAULT))
    T_N = float(params.get('T_N_К', T_N_DEFAULT))
    rho_N = P_N/(R_AIR*T_N)

    all_results = {}
    kpi_rows = []
    flows_rows = []
    energy_rows = []

    for name, test in tests.items():
        df_main, df_drossel, df_energy, nodes, edges, df_energy_edges, df_energy_groups, df_atm = simulate(params, test, dt=1e-3, t_end=3.0)
        all_results[name] = (df_main, df_drossel, df_energy, test.get('описание',''))

        phi_deg = df_main['крен_phi_рад'].to_numpy()*180/math.pi
        th_deg = df_main['тангаж_theta_рад'].to_numpy()*180/math.pi

        kpi_rows.append({
            'тест': name,
            'описание': test.get('описание',''),
            'макс|крен|_град': float(np.max(np.abs(phi_deg))),
            'макс|тангаж|_град': float(np.max(np.abs(th_deg))),
            'конечное_давление_Р1_бар_абс': float(df_main['давление_ресивер1_Па'].iloc[-1]/1e5),
            'конечное_давление_Р2_бар_абс': float(df_main['давление_ресивер2_Па'].iloc[-1]/1e5),
            'конечное_давление_Р3_бар_абс': float(df_main['давление_ресивер3_Па'].iloc[-1]/1e5),
            'конечное_давление_АКК_бар_абс': float(df_main['давление_аккумулятор_Па'].iloc[-1]/1e5),
            'энергия_дроссели_Дж': float(df_energy['энергия_рассеяна_Дж'].sum()),
        })

        dt_local = df_drossel['время_с'].iloc[1] - df_drossel['время_с'].iloc[0]
        for col in df_drossel.columns[1:]:
            m_abs = float(np.sum(np.abs(df_drossel[col].to_numpy()))*dt_local)
            Vn_l = m_abs / rho_N * 1000.0
            flows_rows.append({'тест': name, 'дроссель': col, 'расход_Нл': Vn_l})

        totE = df_energy['энергия_рассеяна_Дж'].sum()
        for _, row in df_energy.iterrows():
            energy_rows.append({
                'тест': name,
                'дроссель': row['дроссель'],
                'энергия_Дж': float(row['энергия_рассеяна_Дж']),
                'доля': float(row['энергия_рассеяна_Дж']/totE if totE>0 else 0)
            })

    df_kpi = pd.DataFrame(kpi_rows)
    df_flows = pd.DataFrame(flows_rows).pivot(index='дроссель', columns='тест', values='расход_Нл').reset_index()
    df_energy_all = pd.DataFrame(energy_rows)

        # Легенда (человеческая) + жёсткая привязка Camozzi по каждому месту схемы
    nodes_df = pd.DataFrame([{
        'узел': n.name,
        'тип_узла': n.kind,
        'объём_м3': float(n.V0),
        'угол': n.corner or '',
        'цилиндр': n.cyl or '',
        'полость': ('бесштоковая' if n.chamber == 'CAP' else 'штоковая') if n.chamber else ''
    } for n in nodes])

    edges_df = pd.DataFrame([{
        'элемент': e.name,
        'узел_вверх': nodes[e.n1].name,
        'узел_вниз': nodes[e.n2].name,
        'тип_элемента': e.kind,
        'Camozzi_код': e.camozzi_код,
        'площадь_эффективная_мм2': float(e.A)*1e6,
        'площадь_максимальная_мм2': (float(e.A_макс)*1e6) if (e.A_макс is not None) else '',
        'alpha_открытия': (float(e.alpha) if e.alpha is not None else ''),
        'перепад_открытия_Па': float(e.dp_crack) if e.dp_crack is not None else '',
        'уставка_Па': float(e.p_set) if e.p_set is not None else '',
        'группа': (e.group or '')
    } for e in edges])

    # Таблица пружины (для "живого" редактирования)
    spring_df = pd.DataFrame({
        'ход_delta_мм': params.get('пружина_таблица_ход_мм', [-125, -80, -40, -20, 0, 20, 50, 80, 125]),
        'сила_добавочная_Н': params.get('пружина_таблица_сила_Н', [-1200, -900, -500, -200, 0, 400, 1200, 2200, 4000]),
    })
    with pd.ExcelWriter(output_path, engine='openpyxl') as writer:
        df_kpi.to_excel(writer, sheet_name='KPI', index=False)
        df_flows.to_excel(writer, sheet_name='Расходы_дроссели_Нл', index=False)
        df_energy_all.to_excel(writer, sheet_name='Энергия_дроссели', index=False)
        nodes_df.to_excel(writer, sheet_name='Узлы', index=False)
        edges_df.to_excel(writer, sheet_name='Элементы', index=False)
        spring_df.to_excel(writer, sheet_name='Пружина', index=False)

        for test_name, (df_main, df_drossel, df_energy, descr) in all_results.items():
            base = re.sub(r'[^0-9A-Za-zА-Яа-я_]+','_', test_name)
            sheet_main = (base[:25] + '_t')[:31]
            sheet_flow = (base[:25] + '_q')[:31]
            df_main.to_excel(writer, sheet_name=sheet_main, index=False)
            df_drossel.to_excel(writer, sheet_name=sheet_flow, index=False)

    return output_path

if __name__ == '__main__':
    run_default_and_export_excel('результаты_полная_тесты_v3_camozzi_пружины.xlsx')
