# -*- coding: utf-8 -*-
"""
Полностью дифференциальная модель (механика + пневматика) по схеме:
- Ц1 (4 цилиндра): двухступенчатый насос: атмосфера -> Ресивер1 -> Ресивер2
- Ц2 (4 цилиндра): третья ступень: Ресивер2 -> диагонали (с дросселями) -> Ресивер3 -> Аккумулятор
- Адаптивные клапана ресивера 3: Pmin/Pmid (сброс) и Pmax (предохранительный)

Состояние:
- Механика: z, phi, theta, z_w[4] + скорости (14 переменных)
- Пневматика: массы воздуха во всех узлах (N переменных)

Математика:
- Газ: идеальный, T=const (изотерма)
- Узлы-ёмкости: p = m R T / V
- Расходы: сжимаемый исток/дроссель (choked/subsonic), обратный клапан = диод с перепадом открытия
- Регулятор "после себя": открывает проток, если p_вниз < уставка
- Регулятор/клапан "до себя" (сброс): открывает проток, если p_вверх > уставка

Выход:
- Excel с KPI/расходами/энергией по дросселям + временные ряды.

Примечание:
Эта версия фокусируется на корректной топологии и дифференциальности модели.
Параметры (уставки, диаметры дросселей, объёмы) вынесены в словарь params и могут оптимизироваться.

(c) generated by ChatGPT
"""

from dataclasses import dataclass
import math
import os
import numpy as np
import pandas as pd
import re


# ---------------------------------------------------------------------
# База компонентов Camozzi (жёсткая привязка по месту)
# Источники:
# - VNR: серия обратных клапанов (Qn и min operating pressure) из официального PDF Camozzi VNR-ENG (2025/05)
# - SCO: серия двунаправленных дросселей (номинальные диаметры по портам) из официального PDF SCU/MCU/SVU/MVU/SCO/MCO (2025/04)
# ---------------------------------------------------------------------

CAMOZZI_VNR = {
    # код: {Qn [Nl/min] при 6 bar, ΔP=1 bar; минимальное рабочее давление (используем как перепад открытия), бар; максимальное давление, бар}
    "VNR-210-1/8":  {"Qn_Nl_min": 600.0,  "dp_откр_бар": 0.2,  "Pmax_бар": 10.0},   # G1/8
    "VNR-843-07":   {"Qn_Nl_min": 1400.0, "dp_откр_бар": 0.2,  "Pmax_бар": 10.0},   # G1/4
    "VNR-238-3/8":  {"Qn_Nl_min": 3000.0, "dp_откр_бар": 0.02, "Pmax_бар": 25.0},   # G3/8
    "VNR-212-1/2":  {"Qn_Nl_min": 5800.0, "dp_откр_бар": 0.02, "Pmax_бар": 25.0},   # G1/2
}

CAMOZZI_SCO = {
    # код: {номинальный диаметр, мм (максимальный); тип}
    "SCO 604-1/8":        {"d_max_мм": 2.0,  "тип": "двунаправленный дроссель (SCO)"},
    "SCO 606-1/4":        {"d_max_мм": 4.0,  "тип": "двунаправленный дроссель (SCO)"},
    "SCO 608-3/8":        {"d_max_мм": 7.0,  "тип": "двунаправленный дроссель (SCO)"},
    "SCO 610-1/2":        {"d_max_мм": 12.0, "тип": "двунаправленный дроссель (SCO)"},
    "SCO 604-1/8+2905":   {"d_max_мм": 2.0,  "тип": "дроссель с глушителем (SCO+2905)"},
    "SCO 606-1/4+2905":   {"d_max_мм": 4.0,  "тип": "дроссель с глушителем (SCO+2905)"},
}


# -------------------------
# Физические константы
# -------------------------
R_AIR = 287.0
T_AIR = 293.15

class RolloverException(RuntimeError):
    """Расчёт прерван: модель предсказала опрокидывание/невалидное состояние."""
    pass

GAMMA = 1.4
P_ATM = 101325.0

# Нормальные условия для пересчёта Qn [Nl/min] -> ṁ (по умолчанию)
# В промышленной практике Nl часто понимают как 0°C и 1 атм (101325 Па).
P_N_DEFAULT = 101325.0
T_N_DEFAULT = 273.15

# -------------------------
# Газодинамика (дроссели)
# -------------------------
def mdot_orifice(p_up: float, p_dn: float, A: float, Cd: float = 0.8) -> float:
    """Массовый расход через отверстие из p_up в p_dn (p_up>p_dn), кг/с."""
    if A <= 0.0:
        return 0.0
    if p_up <= 0.0 or p_dn <= 0.0:
        return 0.0
    if p_up <= p_dn:
        return 0.0

    pr = p_dn / p_up
    pr_crit = (2.0 / (GAMMA + 1.0)) ** (GAMMA / (GAMMA - 1.0))

    if pr <= pr_crit:
        # захлопывание (choked)
        return Cd * A * p_up * math.sqrt(GAMMA / (R_AIR * T_AIR)) * (2.0 / (GAMMA + 1.0)) ** ((GAMMA + 1.0) / (2.0 * (GAMMA - 1.0)))
    else:
        term = pr ** (2.0 / GAMMA) - pr ** ((GAMMA + 1.0) / GAMMA)
        term = max(term, 0.0)
        return Cd * A * p_up * math.sqrt(2.0 * GAMMA / (R_AIR * T_AIR * (GAMMA - 1.0)) * term)

def mdot_orifice_signed(p1: float, p2: float, A: float, Cd: float = 0.8) -> float:
    """Двусторонний дроссель: знак расхода зависит от перепада."""
    if p1 > p2:
        return mdot_orifice(p1, p2, A, Cd)
    elif p2 > p1:
        return -mdot_orifice(p2, p1, A, Cd)
    else:
        return 0.0

def area_from_Qn(Qn_Nl_min: float,
                 p_up_abs: float = None,
                 dp: float = None,
                 Cd: float = 0.8,
                 P_N: float = P_N_DEFAULT,
                 T_N: float = T_N_DEFAULT) -> float:
    """Подбор эквивалентной площади A по номинальному расходу Qn (Nl/min).

    ВАЖНО про Nl/min:
    - 'Nl' (normal litre) обычно означает пересчёт объёмного расхода к нормальным условиям.
      Во многих инженерных источниках нормальные условия принимают как 0°C и 1.01325 bar abs.
    - Чтобы не было скрытой ошибки ~5–10% по проводимости (из‑за ρ_N), условия N вынесены в P_N/T_N.

    Здесь делаем:
        Qn [Nl/min] -> Qn [m³/s] при нормальных условиях -> ṁ_N = ρ_N * Qn
    и подбираем A так, чтобы ṁ_orifice(p_up, p_dn, A) совпал с ṁ_N в паспортной точке (6 bar, ΔP=1 bar).
    """
    # плотность воздуха при нормальных условиях
    rho_N = float(P_N) / (R_AIR * float(T_N))

    # нормальный объёмный расход (м³/с)
    Qn_m3_s = (Qn_Nl_min / 1000.0) / 60.0
    mdot_N = rho_N * Qn_m3_s

    # Паспортная точка Camozzi: подача 6 bar (обычно избыточное) и ΔP=1 bar.
    if p_up_abs is None:
        p_up_abs = P_ATM + 6e5
    if dp is None:
        dp = 1e5
    p_dn_abs = max(P_ATM, p_up_abs - dp)

    base = mdot_orifice(p_up_abs, p_dn_abs, 1.0, Cd)
    if base <= 0.0:
        return 1e-6
    return mdot_N / base

def A_from_diam_mm(d_mm: float) -> float:
    return math.pi * (d_mm * 1e-3 / 2.0) ** 2

# -------------------------
# Сеть узлов/элементов
# -------------------------
@dataclass
class Node:
    name: str
    kind: str  # 'fixed', 'chamber', 'atmos'
    V0: float  # м3 (для chamber это мёртвый объём)
    corner: str = None
    chamber: str = None  # 'CAP'/'ROD'
    cyl: str = None      # 'C1'/'C2'

@dataclass
class Edge:
    name: str
    n1: int
    n2: int
    kind: str  # 'check','orifice','reg_after','relief'
    A: float
    dp_crack: float = 2000.0
    p_set: float = None
    Cd: float = 0.8
    group: str = None
    camozzi_код: str = ''
    A_макс: float = None   # для дросселя (по d_max)
    alpha: float = None    # 0..1 (для дросселя)


corner_order = ['ЛП', 'ПП', 'ЛЗ', 'ПЗ']

def build_network_full(params: dict):
    nodes = []
    node_index = {}
    def add_node(name, kind, V0, corner=None, chamber=None, cyl=None):
        idx = len(nodes)
        nodes.append(Node(name, kind, V0, corner, chamber, cyl))
        node_index[name] = idx
        return idx

    V_R1 = params.get('объём_ресивера_1', 0.0005)
    V_R2 = params.get('объём_ресивера_2', 0.0005)
    V_R3 = params.get('объём_ресивера_3', 0.0010)
    V_ACC = params.get('объём_аккумулятора', 0.0020)
    V_line = params.get('объём_линии', 2e-5)

    # Нормальные условия для параметров Qn [Nl/min] (можно переопределить в params)
    P_N = float(params.get('P_N_Па', P_N_DEFAULT))
    T_N = float(params.get('T_N_К', T_N_DEFAULT))

    add_node('АТМ', 'atmos', 1e-9)
    add_node('Ресивер1', 'fixed', V_R1)
    add_node('Ресивер2', 'fixed', V_R2)
    add_node('Ресивер3', 'fixed', V_R3)
    add_node('Аккумулятор', 'fixed', V_ACC)

    add_node('узел_после_рег_Pmin_питание_Р2', 'fixed', V_line)
    add_node('узел_после_предохран_Pmax', 'fixed', V_line)
    add_node('узел_после_рег_Pmid', 'fixed', V_line)
    add_node('узел_после_ОК_Pmid', 'fixed', V_line)
    add_node('узел_после_рег_Pmin_сброс', 'fixed', V_line)
    add_node('узел_после_ОК_Pmin', 'fixed', V_line)
    add_node('узел_после_рег_заряд_аккумулятора', 'fixed', V_line)

    V0_ch = params.get('мёртвый_объём_камеры', 15e-6)
    for c in corner_order:
        add_node(f'Ц1_{c}_БП', 'chamber', V0_ch, corner=c, chamber='CAP', cyl='C1')
        add_node(f'Ц1_{c}_ШП', 'chamber', V0_ch, corner=c, chamber='ROD', cyl='C1')
        add_node(f'Ц2_{c}_БП', 'chamber', V0_ch, corner=c, chamber='CAP', cyl='C2')
        add_node(f'Ц2_{c}_ШП', 'chamber', V0_ch, corner=c, chamber='ROD', cyl='C2')

    add_node('Магистраль_ЛП2_ПЗ2', 'fixed', V_line)
    add_node('Магистраль_ПП2_ЛЗ2', 'fixed', V_line)

    diag_pairs = [('ЛП', 'ПЗ', 'Магистраль_ЛП2_ПЗ2'), ('ПП', 'ЛЗ', 'Магистраль_ПП2_ЛЗ2')]
    conns = [('CAP', 'ROD'), ('ROD', 'CAP')]
    for a, b, _man in diag_pairs:
        for ch_a, ch_b in conns:
            add_node(f'узел_{a}{ch_a}_к_{b}{ch_b}_междуОКиДР', 'fixed', V_line)
            add_node(f'узел_{a}{ch_a}_к_{b}{ch_b}_послеДР', 'fixed', V_line)
            add_node(f'узел_{b}{ch_b}_к_{a}{ch_a}_междуОКиДР', 'fixed', V_line)
            add_node(f'узел_{b}{ch_b}_к_{a}{ch_a}_послеДР', 'fixed', V_line)

    edges = []
    def add_edge(name, n1_name, n2_name, kind, A, dp_crack=2000.0, p_set=None, Cd=0.8, group=None, camozzi_код='', A_макс=None, alpha=None):
        edges.append(Edge(name, node_index[n1_name], node_index[n2_name], kind, A, dp_crack, p_set, Cd, group, camozzi_код, A_макс, alpha))

    # Эквивалентные площади по конкретным Camozzi-кодам
    def A_по_VNR(код: str):
        d = CAMOZZI_VNR[код]
        return area_from_Qn(d["Qn_Nl_min"], P_N=P_N, T_N=T_N), d["dp_откр_бар"]*1e5

    def A_по_SCO(код: str, alpha: float):
        d = CAMOZZI_SCO[код]
        Amax = A_from_diam_mm(d["d_max_мм"])
        return alpha*Amax, Amax

    # Базовые настройки дросселей (0..1) — дальше это оптимизируемые параметры
    # Два дросселя (две линии) для раздельной настройки: CAP→ROD и ROD→CAP (условно: сжатие/отбой)
    alpha_дроссель_диагональ_CAP_ROD = params.get('открытие_дросселя_Ц2_CAP_в_ROD', 0.35)
    alpha_дроссель_диагональ_ROD_CAP = params.get('открытие_дросселя_Ц2_ROD_в_CAP', 0.35)
    alpha_дроссель_выхлоп_Pmin = params.get('открытие_дросселя_выхлоп_Pmin', 0.30)
    alpha_дроссель_выхлоп_Pmid = params.get('открытие_дросселя_выхлоп_Pmid', 0.45)
    alpha_дроссель_выхлоп_Pmax = params.get('открытие_дросселя_выхлоп_Pmax', 0.70)


    # -------------------------
    # Ц1: атмосфера -> Ресивер1 -> Ресивер2  (2 ступени)
    # -------------------------
    for c in corner_order:
        # Впуск: атмосфера -> бесштоковая полость Ц1
        A, dp = A_по_VNR("VNR-238-3/8")
        add_edge(f'обратный_клапан‑впуск‑атмосфера‑Ц1‑{c}‑бесштоковая',
                 'АТМ', f'Ц1_{c}_БП', 'check', A, dp, group='клапан', camozzi_код="VNR-238-3/8")

        # Выпуск ступени 1: Ц1 бесштоковая -> Ресивер1
        A, dp = A_по_VNR("VNR-238-3/8")
        add_edge(f'обратный_клапан‑выпуск‑Ц1‑{c}‑бесштоковая‑в‑Ресивер1',
                 f'Ц1_{c}_БП', 'Ресивер1', 'check', A, dp, group='клапан', camozzi_код="VNR-238-3/8")

        # Впуск ступени 2: Ресивер1 -> Ц1 штоковая
        A, dp = A_по_VNR("VNR-238-3/8")
        add_edge(f'обратный_клапан‑впуск‑Ресивер1‑в‑Ц1‑{c}‑штоковая',
                 'Ресивер1', f'Ц1_{c}_ШП', 'check', A, dp, group='клапан', camozzi_код="VNR-238-3/8")

        # Выпуск ступени 2: Ц1 штоковая -> Ресивер2
        A, dp = A_по_VNR("VNR-212-1/2")
        add_edge(f'обратный_клапан‑выпуск‑Ц1‑{c}‑штоковая‑в‑Ресивер2',
                 f'Ц1_{c}_ШП', 'Ресивер2', 'check', A, dp, group='клапан', camozzi_код="VNR-212-1/2")

    # Питание Ресивер2 из аккумулятора (регулятор "после себя" + обратный клапан)
    Pmin_feed = params.get('давление_Pmin_питание_Ресивер2', P_ATM + 2e5)
    A, dp = A_по_VNR("VNR-238-3/8")
    add_edge('регулятор‑после‑себя‑Pmin‑питание‑Ресивер2‑из‑Аккумулятор',
             'Аккумулятор', 'узел_после_рег_Pmin_питание_Р2', 'reg_after', A, dp, p_set=Pmin_feed,
             group='регулятор', camozzi_код='MC104-R00 (Series MC)')

    # Обратный клапан после регулятора (чтобы Р2 не сливался в аккумулятор)
    A, dp = A_по_VNR("VNR-238-3/8")
    add_edge('обратный_клапан‑питание‑Ресивер2‑из‑узла‑после‑регулятора',
             'узел_после_рег_Pmin_питание_Р2', 'Ресивер2', 'check', A, dp, group='клапан', camozzi_код="VNR-238-3/8")

    # -------------------------
    # Ц2: впуск из Ресивер2 + диагонали (дроссели) + сбор в Ресивер3
    # -------------------------
    for c in corner_order:
        # Впуск Р2 -> Ц2 (обе полости). Здесь используем 1/4 (реалистично под D50), но с dp=0.2 бар.
        A, dp = A_по_VNR("VNR-843-07")
        add_edge(f'обратный_клапан‑впуск‑Ресивер2‑в‑Ц2‑{c}‑бесштоковая',
                 'Ресивер2', f'Ц2_{c}_БП', 'check', A, dp, group='клапан', camozzi_код="VNR-843-07")
        A, dp = A_по_VNR("VNR-843-07")
        add_edge(f'обратный_клапан‑впуск‑Ресивер2‑в‑Ц2‑{c}‑штоковая',
                 'Ресивер2', f'Ц2_{c}_ШП', 'check', A, dp, group='клапан', camozzi_код="VNR-843-07")

    def ch_node(c, ch):
        return f'Ц2_{c}_БП' if ch == 'CAP' else f'Ц2_{c}_ШП'

    # Диагонали: соединения КАП<->ШТОК, как вы описали (все штоки вниз, перекрёст делаем связями камер)
    for a, b, man in diag_pairs:
        for ch_a, ch_b in conns:
            N_ab = f'узел_{a}{ch_a}_к_{b}{ch_b}_междуОКиДР'
            M_ab = f'узел_{a}{ch_a}_к_{b}{ch_b}_послеДР'
            N_ba = f'узел_{b}{ch_b}_к_{a}{ch_a}_междуОКиДР'
            M_ba = f'узел_{b}{ch_b}_к_{a}{ch_a}_послеДР'

            # --- направление a -> b ---
            # 1) из камеры a через обратный клапан в узел между ОК и ДР
            A, dp = A_по_VNR("VNR-843-07")
            add_edge(f'обратный_клапан‑выход‑из‑Ц2‑{a}‑{ch_a}‑в‑диагональ‑к‑{b}‑{ch_b}',
                     ch_node(a, ch_a), N_ab, 'check', A, dp, group='клапан', camozzi_код="VNR-843-07")

            # 2) из узла между ОК и ДР — ответвление в магистраль (к Р3) через обратный клапан (между ОК и ДР!)
            A, dp = A_по_VNR("VNR-238-3/8")
            add_edge(f'обратный_клапан‑сбор‑в‑магистраль‑{man}‑из‑узла‑{a}{ch_a}к{b}{ch_b}',
                     N_ab, man, 'check', A, dp, group='клапан', camozzi_код="VNR-238-3/8")

            # 3) из узла между ОК и ДР — через дроссель (компр/отбой) к другому цилиндру
            alpha_line = alpha_дроссель_диагональ_CAP_ROD if (ch_a == "CAP" and ch_b == "ROD") else alpha_дроссель_диагональ_ROD_CAP
            A_eff, Amax = A_по_SCO("SCO 606-1/4", alpha_line)
            add_edge(f'дроссель‑диагональ‑Ц2‑линия_{ch_a}→{ch_b}‑{a}{ch_a}→{b}{ch_b}',
                     N_ab, M_ab, 'orifice', A_eff, dp_crack=0.0, group='дроссель',
                     camozzi_код="SCO 606-1/4", A_макс=Amax, alpha=alpha_line)

            # 4) после дросселя — через обратный клапан в камеру b
            A, dp = A_по_VNR("VNR-843-07")
            add_edge(f'обратный_клапан‑вход‑в‑Ц2‑{b}‑{ch_b}‑из‑диагонали‑{a}{ch_a}→{b}{ch_b}',
                     M_ab, ch_node(b, ch_b), 'check', A, dp, group='клапан', camozzi_код="VNR-843-07")

            # --- направление b -> a (симметрично) ---
            A, dp = A_по_VNR("VNR-843-07")
            add_edge(f'обратный_клапан‑выход‑из‑Ц2‑{b}‑{ch_b}‑в‑диагональ‑к‑{a}‑{ch_a}',
                     ch_node(b, ch_b), N_ba, 'check', A, dp, group='клапан', camozzi_код="VNR-843-07")

            A, dp = A_по_VNR("VNR-238-3/8")
            add_edge(f'обратный_клапан‑сбор‑в‑магистраль‑{man}‑из‑узла‑{b}{ch_b}к{a}{ch_a}',
                     N_ba, man, 'check', A, dp, group='клапан', camozzi_код="VNR-238-3/8")

            alpha_line = alpha_дроссель_диагональ_CAP_ROD if (ch_b == "CAP" and ch_a == "ROD") else alpha_дроссель_диагональ_ROD_CAP
            A_eff, Amax = A_по_SCO("SCO 606-1/4", alpha_line)
            add_edge(f'дроссель‑диагональ‑Ц2‑линия_{ch_b}→{ch_a}‑{b}{ch_b}→{a}{ch_a}',
                     N_ba, M_ba, 'orifice', A_eff, dp_crack=0.0, group='дроссель',
                     camozzi_код="SCO 606-1/4", A_макс=Amax, alpha=alpha_line)

            A, dp = A_по_VNR("VNR-843-07")
            add_edge(f'обратный_клапан‑вход‑в‑Ц2‑{a}‑{ch_a}‑из‑диагонали‑{b}{ch_b}→{a}{ch_a}',
                     M_ba, ch_node(a, ch_a), 'check', A, dp, group='клапан', camozzi_код="VNR-843-07")

    # Магистрали -> Ресивер3
    A, dp = A_по_VNR("VNR-212-1/2")
    add_edge('обратный_клапан‑магистраль‑ЛП2ПЗ2‑в‑Ресивер3',
             'Магистраль_ЛП2_ПЗ2', 'Ресивер3', 'check', A, dp, group='клапан', camozzi_код="VNR-212-1/2")
    A, dp = A_по_VNR("VNR-212-1/2")
    add_edge('обратный_клапан‑магистраль‑ПП2ЛЗ2‑в‑Ресивер3',
             'Магистраль_ПП2_ЛЗ2', 'Ресивер3', 'check', A, dp, group='клапан', camozzi_код="VNR-212-1/2")

    # Ресивер3 -> Аккумулятор: регулятор "до себя" (ограничивает/задаёт порог зарядки) + обратный клапан (только заряд)
    Pзаряд_акк = params.get('давление_Pзаряд_аккумулятора_из_Ресивер3', P_ATM + 8e5)
    A_reg, _dp = A_по_VNR("VNR-212-1/2")  # по проходу как крупный
    add_edge('регулятор_до_себя_заряд_аккумулятора_из_Ресивер3',
             'Ресивер3', 'узел_после_рег_заряд_аккумулятора', 'relief', A_reg, dp_crack=0.0, p_set=Pзаряд_акк,
             group='регулятор', camozzi_код='VMR 1/8-B10')

    A, dp = A_по_VNR("VNR-212-1/2")
    add_edge('обратный_клапан‑заряд‑аккумулятора‑после_регулятора',
             'узел_после_рег_заряд_аккумулятора', 'Аккумулятор', 'check', A, dp, group='клапан', camozzi_код="VNR-212-1/2")
# -------------------------
    # Сброс/предохранение Ресивер3 -> АТМ  (адаптивность)
    # -------------------------
    Pmax = params.get('давление_Pmax_предохран', P_ATM + 8e5)
    Pmid = params.get('давление_Pmid_сброс', P_ATM + 4e5)
    Pmin_rel = params.get('давление_Pmin_сброс', P_ATM + 2e5)

    # Предохранительный клапан (эквивалент Camozzi VMR 1/8-B10 как "overpressure exhaust valve")
    # В модели это "relief" элемент: открывается при p(Р3) > Pmax
    A, _dp = A_по_VNR("VNR-212-1/2")  # по пропускной как крупный проход
    add_edge('клапан_предохранительный_Pmax_Ресивер3→узел',
             'Ресивер3', 'узел_после_предохран_Pmax', 'relief', A, dp_crack=0.0, p_set=Pmax,
             group='клапан', camozzi_код='VMR 1/8-B10')

    # Дросселирование на выход в атмосферу (SCO + 2905)
    A_eff, Amax = A_по_SCO("SCO 606-1/4", alpha_дроссель_выхлоп_Pmax)
    add_edge('дроссель_выхлоп_Pmax',
             'узел_после_предохран_Pmax', 'АТМ', 'orifice', A_eff, dp_crack=0.0,
             group='выхлоп', camozzi_код="SCO 606-1/4", A_макс=Amax, alpha=alpha_дроссель_выхлоп_Pmax)

    # Сброс Pmid: регулятор "до себя" (открывается при p(Р3) > Pmid) → обратный клапан → дроссель → атмосфера
    A, _dp = A_по_VNR("VNR-238-3/8")
    add_edge('регулятор_до_себя_Pmid_сброс',
             'Ресивер3', 'узел_после_рег_Pmid', 'relief', A, dp_crack=0.0, p_set=Pmid,
             group='регулятор', camozzi_код='VMR 1/8-B10')

    A, dp = A_по_VNR("VNR-238-3/8")
    add_edge('обратный_клапан_Pmid_к_выхлопу',
             'узел_после_рег_Pmid', 'узел_после_ОК_Pmid', 'check', A, dp,
             group='клапан', camozzi_код="VNR-238-3/8")

    A_eff, Amax = A_по_SCO("SCO 604-1/8", alpha_дроссель_выхлоп_Pmid)
    add_edge('дроссель_выхлоп_Pmid',
             'узел_после_ОК_Pmid', 'АТМ', 'orifice', A_eff, dp_crack=0.0,
             group='выхлоп', camozzi_код="SCO 604-1/8", A_макс=Amax, alpha=alpha_дроссель_выхлоп_Pmid)

    # Сброс Pmin: то же самое, но уставка ниже
    A, _dp = A_по_VNR("VNR-238-3/8")
    add_edge('регулятор_до_себя_Pmin_сброс',
             'Ресивер3', 'узел_после_рег_Pmin_сброс', 'relief', A, dp_crack=0.0, p_set=Pmin_rel,
             group='регулятор', camozzi_код='VMR 1/8-B10')

    A, dp = A_по_VNR("VNR-238-3/8")
    add_edge('обратный_клапан_Pmin_к_выхлопу',
             'узел_после_рег_Pmin_сброс', 'узел_после_ОК_Pmin', 'check', A, dp,
             group='клапан', camozzi_код="VNR-238-3/8")

    A_eff, Amax = A_по_SCO("SCO 604-1/8", alpha_дроссель_выхлоп_Pmin)
    add_edge('дроссель_выхлоп_Pmin',
             'узел_после_ОК_Pmin', 'АТМ', 'orifice', A_eff, dp_crack=0.0,
             group='выхлоп', camozzi_код="SCO 604-1/8", A_макс=Amax, alpha=alpha_дроссель_выхлоп_Pmin)

# Матрица инцидентности
    N = len(nodes)
    E = len(edges)
    B = np.zeros((N, E))
    for ei, e in enumerate(edges):
        B[e.n1, ei] -= 1.0
        B[e.n2, ei] += 1.0

    return nodes, node_index, edges, B

# -------------------------
# Моделирование
# -------------------------
def simulate(params: dict, test: dict, dt: float = 1e-3, t_end: float = 3.0, record_full: bool = False):
    nodes, node_index, edges, B = build_network_full(params)

    # --- Scheme integrity (topology lock) ---
    # Для v8-подобных схем используем отдельный отпечаток.
    try:
        from .scheme_integrity import assert_fingerprint, assert_camozzi_only  # type: ignore
    except Exception:
        from scheme_integrity import assert_fingerprint, assert_camozzi_only  # type: ignore

    if bool(params.get('enforce_scheme_integrity', True)):
        fp_file = str(params.get('scheme_fingerprint_file', 'scheme_fingerprint_v8_r48.json'))
        if not os.path.isabs(fp_file):
            fp_file = os.path.join(os.path.dirname(__file__), fp_file)
        assert_fingerprint(nodes, edges, fp_file)

    if bool(params.get('enforce_camozzi_only', True)):
        pp_file = str(params.get('паспорт_компонентов_json', params.get('passport_components_json', 'component_passport.json')))
        if not os.path.isabs(pp_file):
            pp_file = os.path.join(os.path.dirname(__file__), pp_file)
        assert_camozzi_only(edges, pp_file)
    N = len(nodes)
    E = len(edges)

    # Геометрия шасси
    wheelbase = params.get('база', 2.3)
    track = params.get('колея', 1.2)
    x_pos = np.array([ wheelbase/2,  wheelbase/2, -wheelbase/2, -wheelbase/2])
    y_pos = np.array([ track/2, -track/2,  track/2, -track/2])

    # Массы
    m_body = params.get('масса_рамы', 600.0)
    m_w = params.get('масса_неподрессоренная_на_угол', 15.0)
    g = 9.81

    # Габариты рамы (для момента инерции) — 1/2/6, ширина=0.3*колеи
    W = params.get('ширина_рамы', 0.3*track)
    H = params.get('высота_рамы', 2*W)
    L = params.get('длина_рамы', 6*W)
    I_roll = (1.0/12.0) * m_body * (W**2 + H**2)
    I_pitch= (1.0/12.0) * m_body * (L**2 + H**2)

    # Грубая оценка критического угла опрокидывания (проекция ЦМ выходит за опору)
    h_cg = float(params.get('высота_центра_масс', H/2.0))
    phi_crit = math.atan((track/2.0)/max(1e-6, h_cg))
    theta_crit = math.atan((wheelbase/2.0)/max(1e-6, h_cg))

    # Аварийный предел для остановки интегрирования (чтобы не улетать в невалидную геометрию).
    # Критические углы (phi_crit/theta_crit) используем как KPI («запас до пробоя»), а не как стоп.
    phi_abort_deg = float(params.get('аварийный_предел_крен_град', 85.0))
    theta_abort_deg = float(params.get('аварийный_предел_тангаж_град', 85.0))
    phi_abort = math.radians(phi_abort_deg)
    theta_abort = math.radians(theta_abort_deg)

    k_tire = params.get('жёсткость_шины', 200000.0)
    c_tire = params.get('демпфирование_шины', 2000.0)
    # Нелинейная пружина: табличная (кусочно-линейная) характеристика
    # delta = z_колеса - z_рамы_в_углу (м): delta>0 = сжатие подвески
    табл_пруж_ход_мм = np.array(params.get('пружина_таблица_ход_мм', [-125, -80, -40, -20, 0, 20, 50, 80, 125]), dtype=float)
    табл_пруж_сила_Н = np.array(params.get('пружина_таблица_сила_Н', [-1200, -900, -500, -200, 0, 400, 1200, 2200, 4000]), dtype=float)
    масштаб_пружины = float(params.get('пружина_масштаб', 1.0))
    табл_пруж_ход_м = табл_пруж_ход_мм * 1e-3

    # ВАЖНО: пружина односторонняя (только на сжатие).
    # Если в базе случайно заданы отрицательные точки — в модели их игнорируем.
    mask = (табл_пруж_ход_м >= 0.0) & (табл_пруж_сила_Н >= 0.0)
    if np.any(mask):
        табл_пруж_ход_м = табл_пруж_ход_м[mask]
        табл_пруж_сила_Н = табл_пруж_сила_Н[mask]
    order = np.argsort(табл_пруж_ход_м)
    табл_пруж_ход_м = табл_пруж_ход_м[order]
    табл_пруж_сила_Н = tab_F = np.maximum.accumulate(табл_пруж_сила_Н[order])

    # Геометрия цилиндров
    D1 = params.get('диаметр_поршня_Ц1', 0.032)
    d1 = params.get('диаметр_штока_Ц1', 0.016)
    D2 = params.get('диаметр_поршня_Ц2', 0.050)
    d2 = params.get('диаметр_штока_Ц2', 0.014)
    A1_cap = math.pi*(D1/2)**2
    A1_rod = A1_cap - math.pi*(d1/2)**2
    A2_cap = math.pi*(D2/2)**2
    A2_rod = A2_cap - math.pi*(d2/2)**2

    L_stroke = params.get('ход_штока', 0.250)
    s0 = L_stroke/2.0

    # Массивы камер
    V0_vec = np.array([n.V0 for n in nodes], dtype=float)
    chamber_indices = []
    chamber_corner = []
    chamber_sign = []
    chamber_area = []
    chamber_offset = []
    for i, n in enumerate(nodes):
        if n.kind == 'chamber':
            chamber_indices.append(i)
            chamber_corner.append(corner_order.index(n.corner))
            if n.cyl == 'C1':
                A = A1_cap if n.chamber == 'CAP' else A1_rod
            else:
                A = A2_cap if n.chamber == 'CAP' else A2_rod
            if n.chamber == 'CAP':
                sign = +1.0
                offset = n.V0
            else:
                sign = -1.0
                offset = n.V0 + A * L_stroke
            chamber_sign.append(sign)
            chamber_area.append(A)
            chamber_offset.append(offset)

    chamber_indices = np.array(chamber_indices, dtype=int)
    chamber_corner = np.array(chamber_corner, dtype=int)
    chamber_sign = np.array(chamber_sign, dtype=float)
    chamber_area = np.array(chamber_area, dtype=float)
    chamber_offset = np.array(chamber_offset, dtype=float)

    # -------------------------
    # Начальные давления
    # -------------------------
    Pmin_abs = params.get('давление_Pmin_сброс', P_ATM + 2e5)
    Pacc_abs = params.get('начальное_давление_аккумулятора', P_ATM + 6e5)

    p0 = np.ones(N) * Pmin_abs
    p0[node_index['АТМ']] = P_ATM
    p0[node_index['Ресивер1']] = P_ATM
    p0[node_index['Аккумулятор']] = Pacc_abs
    for c in corner_order:
        p0[node_index[f'Ц1_{c}_БП']] = P_ATM
    for name in ['узел_после_предохран_Pmax','узел_после_рег_Pmid','узел_после_ОК_Pmid','узел_после_рег_Pmin_сброс','узел_после_ОК_Pmin','узел_после_рег_заряд_аккумулятора']:
        p0[node_index[name]] = P_ATM
    p0[node_index['узел_после_рег_Pmin_питание_Р2']] = Pmin_abs

    # Начальная статика (delta=0), шина держит массу
    z_static = -(m_body*g/4.0 + m_w*g) / k_tire
    z0 = z_static
    phi0 = 0.0
    th0 = 0.0
    zw0 = np.ones(4) * z_static
    z_dot0 = phi_dot0 = th_dot0 = 0.0
    zw_dot0 = np.zeros(4)

    # Преднатяг пружин (учёт стартового усилия от пневматики)
    def F_cyl_total_at_p(p_vec):
        F = []
        for cname in corner_order:
            p1c = p_vec[node_index[f'Ц1_{cname}_БП']]
            p1r = p_vec[node_index[f'Ц1_{cname}_ШП']]
            p2c = p_vec[node_index[f'Ц2_{cname}_БП']]
            p2r = p_vec[node_index[f'Ц2_{cname}_ШП']]
            F1 = (p1c - P_ATM) * A1_cap - (p1r - P_ATM) * A1_rod
            F2 = (p2c - P_ATM) * A2_cap - (p2r - P_ATM) * A2_rod
            F.append(F1 + F2)
        return np.array(F)

    F_cyl0 = F_cyl_total_at_p(p0)
    # Пружина: предсжатие (x0) вместо постоянного смещения силы.
    # Требование: таблица только для сжатия (x>=0, F>=0), а в динамике x = max(0, x0 + delta).
    L_free = float(params.get('пружина_длина_свободная_м', float(табл_пруж_ход_м[-1]) if len(табл_пруж_ход_м) else 0.30))
    L_free = max(0.0, L_free)

    F_spr_static_target = m_body*g/4.0 - float(np.mean(F_cyl0))
    F_spr_static_target = max(0.0, F_spr_static_target)
    F_tab_target = F_spr_static_target / max(1e-9, масштаб_пружины)

    if len(табл_пруж_ход_м) >= 2:
        x0 = float(np.interp(
            F_tab_target,
            табл_пруж_сила_Н,
            табл_пруж_ход_м,
            left=float(табл_пруж_ход_м[0]),
            right=float(табл_пруж_ход_м[-1])
        ))
    else:
        x0 = 0.0

    x0 = float(min(max(0.0, x0), L_free))

    # Функция объёмов (дифференциальная)
    def volumes(z, phi, theta, zw, z_dot, phi_dot, theta_dot, zw_dot):
        V = V0_vec.copy()
        dV = np.zeros_like(V)

        z_body = z + math.sin(phi)*y_pos*math.cos(theta) - math.sin(theta)*x_pos
        delta = zw - z_body

        s = np.clip(s0 - delta, 0.0, L_stroke)

        z_body_dot = (z_dot
                     + (math.cos(phi)*y_pos*math.cos(theta))*phi_dot
                     + (math.sin(phi)*y_pos*(-math.sin(theta)))*theta_dot
                     - (x_pos*math.cos(theta))*theta_dot)
        delta_dot = zw_dot - z_body_dot
        s_dot = -delta_dot

        V[chamber_indices] = chamber_offset + chamber_sign*chamber_area*s[chamber_corner]
        dV[chamber_indices] = chamber_sign*chamber_area*s_dot[chamber_corner]
        return V, dV, delta, s, s_dot

    V_init, *_ = volumes(z0, phi0, th0, zw0, z_dot0, phi_dot0, th_dot0, zw_dot0)
    m0 = p0 * V_init / (R_AIR * T_AIR)
    m0[node_index['АТМ']] = P_ATM * V0_vec[node_index['АТМ']] / (R_AIR * T_AIR)

    # Состояние
    state0 = np.concatenate([
        np.array([z0, phi0, th0]),
        zw0,
        np.array([z_dot0, phi_dot0, th_dot0]),
        zw_dot0,
        m0
    ])

    # Внешние воздействия
    ay_func = test.get('ay_func', lambda t: 0.0)
    ax_func = test.get('ax_func', lambda t: 0.0)
    road_func = test.get('road_func', lambda t: np.zeros(4))
    label_func = test.get('label_func', lambda t: 0)

    # Производная профиля дороги (для корректного демпфирования шин при base-excitation).
    road_func_dot = test.get('road_func_dot', None)
    road_dot_eps = float(params.get('road_dot_eps', 1e-4))
    road_dot_eps = max(1e-9, road_dot_eps)

    def _road_vec(v):
        a = np.asarray(v, dtype=float)
        if a.shape == ():
            a = np.full(4, float(a))
        if a.size != 4:
            a = np.resize(a, 4).astype(float)
        return a

    def road_z(t):
        return _road_vec(road_func(t))

    def road_zdot(t):
        if callable(road_func_dot):
            return _road_vec(road_func_dot(t))
        z_p = _road_vec(road_func(t + road_dot_eps))
        z_m = _road_vec(road_func(t - road_dot_eps))
        return (z_p - z_m) / (2.0 * road_dot_eps)

    def compute_pressures(state):
        z, phi, theta = state[0], state[1], state[2]
        zw = state[3:7]
        z_dot, phi_dot, theta_dot = state[7], state[8], state[9]
        zw_dot = state[10:14]
        m = state[14:].copy()

        V, dV, delta, s, s_dot = volumes(z, phi, theta, zw, z_dot, phi_dot, theta_dot, zw_dot)

        # атмосфера как граничное условие + допускаем вакуум (p_abs может быть ниже P_ATM, но не ниже p_abs_min)
        p_abs_min = float(params.get('минимальное_абсолютное_давление_Па', 1000.0))

        # атмосфера (граничное условие)
        m[node_index['АТМ']] = P_ATM * V0_vec[node_index['АТМ']] / (R_AIR * T_AIR)

        V_safe = np.maximum(1e-9, V)

        # Жёстко обеспечиваем физичность: m >= p_abs_min*V/(R*T)  ⇔  p_abs >= p_abs_min
        m_floor = (p_abs_min * V_safe) / (R_AIR * T_AIR)
        m = np.maximum(m, m_floor)

        p = m * R_AIR * T_AIR / V_safe
        p[node_index['АТМ']] = P_ATM
        return p, V, dV, delta, s, s_dot

    # Параметры сглаживания логики клапанов (для дифференцируемости)
    # Если smooth_valves=False — поведение полностью как раньше (жёсткие if).
    smooth_valves = bool(params.get('smooth_valves', False))
    k_smooth_valves = float(params.get('k_smooth_valves', 80.0))  # чем больше, тем резче (ближе к step)

    def _gate01(x: float) -> float:
        """Гладкий аналог Heaviside(x): возвращает значение в [0;1]."""
        # 0.5*(1+tanh(.)) — численно устойчивее, чем exp для больших k*x
        return 0.5 * (1.0 + math.tanh(0.5 * k_smooth_valves * x))

    def compute_flows(p):
        mdots = np.zeros(E)
        for ei, e in enumerate(edges):
            pu = p[e.n1]
            pdn = p[e.n2]

            if e.kind == 'orifice':
                # Двусторонний дроссель (может менять направление)
                mdots[ei] = mdot_orifice_signed(pu, pdn, e.A, e.Cd)

            elif e.kind == 'check':
                if smooth_valves:
                    g = _gate01(pu - pdn - e.dp_crack)
                    mdots[ei] = g * mdot_orifice(pu, pdn, e.A, e.Cd)
                else:
                    mdots[ei] = mdot_orifice(pu, pdn, e.A, e.Cd) if pu > pdn + e.dp_crack else 0.0

            elif e.kind == 'reg_after':
                if smooth_valves:
                    # Открываем, если downstream ниже уставки, и есть перепад на открытие
                    g1 = _gate01(e.p_set - pdn)              # p_dn < p_set
                    g2 = _gate01(pu - pdn - e.dp_crack)      # pu > pdn + dp_crack
                    mdots[ei] = (g1 * g2) * mdot_orifice(pu, pdn, e.A, e.Cd)
                else:
                    if (p[e.n2] < e.p_set) and (pu > pdn + e.dp_crack):
                        mdots[ei] = mdot_orifice(pu, pdn, e.A, e.Cd)
                    else:
                        mdots[ei] = 0.0

            elif e.kind == 'relief':
                if smooth_valves:
                    # Открываем, если upstream выше уставки, и поток вообще возможен (pu>pdn)
                    g1 = _gate01(pu - e.p_set)
                    g2 = _gate01(pu - pdn)
                    mdots[ei] = (g1 * g2) * mdot_orifice(pu, pdn, e.A, e.Cd)
                else:
                    if (pu > e.p_set) and (pu > pdn):
                        mdots[ei] = mdot_orifice(pu, pdn, e.A, e.Cd)
                    else:
                        mdots[ei] = 0.0
        return mdots

    def rhs(state, t):
        """Правая часть ОДУ (без логирования!). Логирование делается снаружи,
        иначе при RK2 второй вызов rhs(mid, t+dt) перетирает значения в out[k]."""
        z, phi, theta = state[0], state[1], state[2]
        zw = state[3:7]
        z_dot, phi_dot, theta_dot = state[7], state[8], state[9]
        zw_dot = state[10:14]

        p, V, dV, delta, s, s_dot = compute_pressures(state)
        mdots = compute_flows(p)

        dm_dt = B @ mdots
        dm_dt[node_index['АТМ']] = 0.0

        # Силы подвески (пружина + пневмоцилиндры)
        z_body = z + math.sin(phi)*y_pos*math.cos(theta) - math.sin(theta)*x_pos
        delta = zw - z_body

        # Односторонняя пружина: работает только на сжатие.
        x = x0 + delta
        x_comp = np.clip(x, 0.0, L_free)
        F_inc = np.interp(x_comp, табл_пруж_ход_м, табл_пруж_сила_Н)
        F_spr = масштаб_пружины * F_inc

        # Силы от Ц1+Ц2 на каждом углу
        F_cyl = np.zeros(4)
        for i_c, cname in enumerate(corner_order):
            p1c = p[node_index[f'Ц1_{cname}_БП']]
            p1r = p[node_index[f'Ц1_{cname}_ШП']]
            p2c = p[node_index[f'Ц2_{cname}_БП']]
            p2r = p[node_index[f'Ц2_{cname}_ШП']]
            F1 = (p1c - P_ATM) * A1_cap - (p1r - P_ATM) * A1_rod
            F2 = (p2c - P_ATM) * A2_cap - (p2r - P_ATM) * A2_rod
            F_cyl[i_c] = F1 + F2

        F_susp = F_spr + F_cyl

        # Отбойники/ограничители хода
        k_stop = float(params.get('жёсткость_отбойника', 1.0e6))
        c_stop = float(params.get('демпфирование_отбойника', 5.0e3))
        delta_max = +L_stroke/2.0
        delta_min = -L_stroke/2.0
        # Важно: delta_dot берём кинематически (zw_dot - z_body_dot), а НЕ из -s_dot,
        # потому что s_dot может быть принудительно «заморожен» при достижении упора штока.
        z_body_dot = (z_dot
                      + (math.cos(phi)*y_pos*math.cos(theta))*phi_dot
                      + (math.sin(phi)*y_pos*(-math.sin(theta)))*theta_dot
                      - (x_pos*math.cos(theta))*theta_dot)
        delta_dot = zw_dot - z_body_dot
        F_stop = np.zeros(4)
        over = delta - delta_max
        F_stop += np.where(over > 0.0, k_stop*over + c_stop*np.maximum(delta_dot, 0.0), 0.0)
        under = delta_min - delta
        F_stop -= np.where(under > 0.0, k_stop*under + c_stop*np.maximum(-delta_dot, 0.0), 0.0)
        F_susp = F_susp + F_stop

        # Моменты от сил и инерции (аппроксимация через высоту ЦМ h_cg)
        M_roll = np.sum(F_susp * y_pos) + m_body*ay_func(t)*h_cg
        # θ>0 — «нос вниз», при ax>0 инерционный момент должен быть «нос вверх» => знак минус
        M_pitch = -np.sum(F_susp * x_pos) - m_body*ax_func(t)*h_cg

        z_ddot = (np.sum(F_susp) - m_body*g) / m_body
        phi_ddot = M_roll / I_roll
        theta_ddot = M_pitch / I_pitch

        # Колёса и контакт (односторонний)
        z_road = road_z(t)
        z_road_dot = road_zdot(t)
        pen = (z_road - zw)
        # Важно: демпфер шины должен видеть относительную скорость (дорога - колесо)
        pen_dot = z_road_dot - zw_dot
        F_tire = np.where(pen > 0.0, k_tire*pen + c_tire*np.maximum(pen_dot, 0.0), 0.0)
        zw_ddot = (F_tire - F_susp - m_w*g) / m_w

        dst = np.zeros_like(state)
        dst[0] = z_dot
        dst[1] = phi_dot
        dst[2] = theta_dot
        dst[3:7] = zw_dot
        dst[7] = z_ddot
        dst[8] = phi_ddot
        dst[9] = theta_ddot
        dst[10:14] = zw_ddot
        dst[14:] = dm_dt
        return dst
    # -------------------------
    # Интегрирование (RK2)
    # -------------------------
    try:
        from .time_grid import build_time_grid
    except Exception:
        from time_grid import build_time_grid
    time = build_time_grid(dt=float(dt), t_end=float(t_end), t0=0.0, mode="floor")
    n_steps = len(time)

    drossel_edges = [ei for ei, e in enumerate(edges) if e.group == 'дроссель']
    drossel_names = [edges[ei].name for ei in drossel_edges]
    mdot_drossel = np.zeros((n_steps, len(drossel_edges)))
    E_drossel = np.zeros(len(drossel_edges))

    # Энерго‑аудит по всем сопротивлениям (дроссели/выхлоп/клапаны/регуляторы)
    # Мощность потерь аппрокс.: N_потерь = Δp * Q_up, где Q_up = |ṁ| / ρ_up.
    # Для двунаправленного дросселя upstream определяется знаком ṁ.
    diss_edges = [ei for ei, e in enumerate(edges) if e.kind in ('orifice','check','reg_after','relief')]
    diss_names = [edges[ei].name for ei in diss_edges]
    diss_groups = [(edges[ei].group or '') for ei in diss_edges]
    diss_kinds = [edges[ei].kind for ei in diss_edges]
    diss_camozzi = [edges[ei].camozzi_код for ei in diss_edges]
    E_diss = np.zeros(len(diss_edges))
    M_diss = np.zeros(len(diss_edges))   # интеграл |ṁ| dt (кг)
    M_to_atm = 0.0
    M_from_atm = 0.0
    idx_atm = node_index['АТМ']
    P_N = float(params.get('P_N_Па', P_N_DEFAULT))
    T_N = float(params.get('T_N_К', T_N_DEFAULT))
    rho_N = P_N/(R_AIR*T_N)

    # Полные записи для UI (по требованию): давления во всех узлах + расходы во всех рёбрах
    p_full = np.zeros((n_steps, N), dtype=float) if record_full else None
    mdot_full = np.zeros((n_steps, E), dtype=float) if record_full else None
    open_full = np.zeros((n_steps, E), dtype=np.int8) if record_full else None

    out = {
        'время_с': time,
        'перемещение_рамы_z_м': np.zeros(n_steps),
        'крен_phi_рад': np.zeros(n_steps),
        'тангаж_theta_рад': np.zeros(n_steps),

        # Внешние воздействия (для анализа инерция/дорога)
        'ускорение_продольное_ax_м_с2': np.zeros(n_steps),
        'ускорение_поперечное_ay_м_с2': np.zeros(n_steps),
        'сегмент_id': np.zeros(n_steps, dtype=int),

        # Колёса
        'перемещение_колеса_ЛП_м': np.zeros(n_steps),
        'перемещение_колеса_ПП_м': np.zeros(n_steps),
        'перемещение_колеса_ЛЗ_м': np.zeros(n_steps),
        'перемещение_колеса_ПЗ_м': np.zeros(n_steps),

        # Штоки цилиндров (положение 0..ход_штока) и скорость (для KPI по упорам/скоростям)
        # В данной кинематической схеме оба цилиндра на углу (Ц1 и Ц2) имеют одинаковый ход штока.
        'положение_штока_ЛП_м': np.zeros(n_steps),
        'положение_штока_ПП_м': np.zeros(n_steps),
        'положение_штока_ЛЗ_м': np.zeros(n_steps),
        'положение_штока_ПЗ_м': np.zeros(n_steps),
        'скорость_штока_ЛП_м_с': np.zeros(n_steps),
        'скорость_штока_ПП_м_с': np.zeros(n_steps),
        'скорость_штока_ЛЗ_м_с': np.zeros(n_steps),
        'скорость_штока_ПЗ_м_с': np.zeros(n_steps),
        'нормальная_сила_шины_ЛП_Н': np.zeros(n_steps),
        'нормальная_сила_шины_ПП_Н': np.zeros(n_steps),
        'нормальная_сила_шины_ЛЗ_Н': np.zeros(n_steps),
        'нормальная_сила_шины_ПЗ_Н': np.zeros(n_steps),
        'колесо_в_воздухе_ЛП': np.zeros(n_steps, dtype=int),
        'колесо_в_воздухе_ПП': np.zeros(n_steps, dtype=int),
        'колесо_в_воздухе_ЛЗ': np.zeros(n_steps, dtype=int),
        'колесо_в_воздухе_ПЗ': np.zeros(n_steps, dtype=int),

        # Дорога под каждым колесом
        'дорога_ЛП_м': np.zeros(n_steps),
        'дорога_ПП_м': np.zeros(n_steps),
        'дорога_ЛЗ_м': np.zeros(n_steps),
        'дорога_ПЗ_м': np.zeros(n_steps),

        # Давления (ключевые)
        'давление_ресивер1_Па': np.zeros(n_steps),
        'давление_ресивер2_Па': np.zeros(n_steps),
        'давление_ресивер3_Па': np.zeros(n_steps),
        'давление_аккумулятор_Па': np.zeros(n_steps),
    }

    state = state0.copy()
    for k, t in enumerate(time):
        out['перемещение_рамы_z_м'][k] = state[0]
        out['крен_phi_рад'][k] = state[1]
        out['тангаж_theta_рад'][k] = state[2]

        # Логируем внешние воздействия (для разделения инерции и дороги)
        out['ускорение_продольное_ax_м_с2'][k] = float(ax_func(t))
        out['ускорение_поперечное_ay_м_с2'][k] = float(ay_func(t))
        out['сегмент_id'][k] = int(label_func(t))

        # Опрокидывание: аварийная остановка (только если совсем вышли за разумные углы)
        # А «запас до опрокидывания» считаем в KPI отдельной непрерывной метрикой.
        if (abs(state[1]) > phi_abort) or (abs(state[2]) > theta_abort):
            raise RolloverException(f"Аварийная остановка (углы): phi={state[1]:.3f} рад, theta={state[2]:.3f} рад")

        out['перемещение_колеса_ЛП_м'][k] = state[3]
        out['перемещение_колеса_ПП_м'][k] = state[4]
        out['перемещение_колеса_ЛЗ_м'][k] = state[5]
        out['перемещение_колеса_ПЗ_м'][k] = state[6]

        p, V, dV, delta, s, s_dot = compute_pressures(state)

        # Лог штоков (положение/скорость) — нужны для KPI по упорам/скоростям
        out['положение_штока_ЛП_м'][k] = float(s[0])
        out['положение_штока_ПП_м'][k] = float(s[1])
        out['положение_штока_ЛЗ_м'][k] = float(s[2])
        out['положение_штока_ПЗ_м'][k] = float(s[3])
        out['скорость_штока_ЛП_м_с'][k] = float(s_dot[0])
        out['скорость_штока_ПП_м_с'][k] = float(s_dot[1])
        out['скорость_штока_ЛЗ_м_с'][k] = float(s_dot[2])
        out['скорость_штока_ПЗ_м_с'][k] = float(s_dot[3])

        # Дорога и контактные реакции шин (для контроля отрыва)
        z_road = road_z(t)
        z_road_dot = road_zdot(t)
        zw = state[3:7]
        zw_dot = state[10:14]
        pen = (z_road - zw)
        # Важно: демпфер шины должен видеть относительную скорость (дорога - колесо)
        pen_dot = z_road_dot - zw_dot
        F_tire = np.where(pen > 0.0, k_tire*pen + c_tire*np.maximum(pen_dot, 0.0), 0.0)

        out['дорога_ЛП_м'][k] = z_road[0]
        out['дорога_ПП_м'][k] = z_road[1]
        out['дорога_ЛЗ_м'][k] = z_road[2]
        out['дорога_ПЗ_м'][k] = z_road[3]

        out['нормальная_сила_шины_ЛП_Н'][k] = F_tire[0]
        out['нормальная_сила_шины_ПП_Н'][k] = F_tire[1]
        out['нормальная_сила_шины_ЛЗ_Н'][k] = F_tire[2]
        out['нормальная_сила_шины_ПЗ_Н'][k] = F_tire[3]

        out['колесо_в_воздухе_ЛП'][k] = int(F_tire[0] <= 1.0)
        out['колесо_в_воздухе_ПП'][k] = int(F_tire[1] <= 1.0)
        out['колесо_в_воздухе_ЛЗ'][k] = int(F_tire[2] <= 1.0)
        out['колесо_в_воздухе_ПЗ'][k] = int(F_tire[3] <= 1.0)
        out['давление_ресивер1_Па'][k] = p[node_index['Ресивер1']]
        out['давление_ресивер2_Па'][k] = p[node_index['Ресивер2']]
        out['давление_ресивер3_Па'][k] = p[node_index['Ресивер3']]
        out['давление_аккумулятор_Па'][k] = p[node_index['Аккумулятор']]

        mdots = compute_flows(p)

        if record_full:
            p_full[k, :] = p
            mdot_full[k, :] = mdots
            # Флаг открытия (упрощённо): 1 если элемент в «открытом» режиме по условию
            for ei, e in enumerate(edges):
                if e.kind == 'check':
                    open_full[k, ei] = 1 if (p[e.n1] > p[e.n2] + e.dp_crack) else 0
                elif e.kind == 'relief':
                    open_full[k, ei] = 1 if (p[e.n1] > e.p_set and p[e.n1] > p[e.n2]) else 0
                elif e.kind == 'reg_after':
                    open_full[k, ei] = 1 if (p[e.n2] < e.p_set and p[e.n1] > p[e.n2] + e.dp_crack) else 0
                else:
                    open_full[k, ei] = 0
        for j, ei in enumerate(drossel_edges):
            md = mdots[ei]
            mdot_drossel[k, j] = md

            # upstream по направлению фактического потока (важно для двунаправленного дросселя)
            e = edges[ei]
            if md >= 0.0:
                up = e.n1
                dn = e.n2
            else:
                up = e.n2
                dn = e.n1

            pu = p[up]
            pdn = p[dn]
            dp_pos = max(0.0, pu - pdn)
            rho_up = max(1e-3, pu / (R_AIR * T_AIR))
            Q_up = abs(md) / rho_up

            E_drossel[j] += dp_pos * Q_up * dt

        # Энерго‑аудит по всем сопротивлениям
        for j, ei in enumerate(diss_edges):
            md = mdots[ei]
            if md == 0.0:
                continue
            e = edges[ei]
            # направление фактического потока
            if md >= 0.0:
                up = e.n1
                dn = e.n2
            else:
                up = e.n2
                dn = e.n1
            pu = p[up]
            pdn = p[dn]
            dp_pos = max(0.0, pu - pdn)
            rho_up = max(1e-3, pu/(R_AIR*T_AIR))
            Q_up = abs(md)/rho_up
            E_diss[j] += dp_pos * Q_up * dt
            M_diss[j] += abs(md) * dt
            if dn == idx_atm:
                M_to_atm += abs(md) * dt
            if up == idx_atm:
                M_from_atm += abs(md) * dt

        if k < n_steps - 1:
            k1vec = rhs(state, t)
            mid = state + dt*k1vec
            k2vec = rhs(mid, t+dt)
            state = state + 0.5*dt*(k1vec + k2vec)

            # Проекция масс: не даём уйти в отрицательные массы и удерживаем p_abs >= p_abs_min (допускаем вакуум)
            p_abs_min = float(params.get('минимальное_абсолютное_давление_Па', 1000.0))
            z_, phi_, theta_ = state[0], state[1], state[2]
            zw_ = state[3:7]
            z_dot_, phi_dot_, theta_dot_ = state[7], state[8], state[9]
            zw_dot_ = state[10:14]
            V_tmp, _, _, _, _ = volumes(z_, phi_, theta_, zw_, z_dot_, phi_dot_, theta_dot_, zw_dot_)
            V_safe = np.maximum(1e-9, V_tmp)
            m_floor = (p_abs_min * V_safe) / (R_AIR * T_AIR)

            m_state = state[14:]
            m_state = np.maximum(m_state, m_floor)

            # атмосфера фиксирована
            m_state[node_index['АТМ']] = P_ATM * V0_vec[node_index['АТМ']] / (R_AIR * T_AIR)

            state[14:] = m_state

    df_main = pd.DataFrame(out)
    df_drossel = pd.DataFrame(mdot_drossel, columns=drossel_names)
    df_drossel.insert(0, 'время_с', time)
    df_energy = pd.DataFrame({
        'дроссель': drossel_names,
        'энергия_рассеяна_Дж': E_drossel
    })

    # Полный энерго‑аудит по всем сопротивлениям
    Vn_l = (M_diss / rho_N) * 1000.0  # Нормальные литры (Нл), интеграл |ṁ| dt / ρ_N
    df_energy_edges = pd.DataFrame({
        'элемент': diss_names,
        'тип_элемента': diss_kinds,
        'группа': [g if g else 'прочее' for g in diss_groups],
        'Camozzi_код': diss_camozzi,
        'энергия_Дж': E_diss,
        'объём_Нл_абс': Vn_l,
    })
    E_total = float(df_energy_edges['энергия_Дж'].sum())
    if E_total > 0.0:
        df_energy_edges['доля_энергии'] = df_energy_edges['энергия_Дж'] / E_total
    else:
        df_energy_edges['доля_энергии'] = 0.0

    df_energy_groups = df_energy_edges.groupby('группа', as_index=False)['энергия_Дж'].sum()
    if E_total > 0.0:
        df_energy_groups['доля_энергии'] = df_energy_groups['энергия_Дж'] / E_total
    else:
        df_energy_groups['доля_энергии'] = 0.0

    df_atm = pd.DataFrame([{
        'масса_в_атмосферу_кг': float(M_to_atm),
        'масса_из_атмосферы_кг': float(M_from_atm),
        'баланс_массы_кг': float(M_from_atm - M_to_atm)
    }])
    if record_full:
        df_p = pd.DataFrame(p_full, columns=[n.name for n in nodes])
        df_p.insert(0, 'время_с', time)
        df_mdot = pd.DataFrame(mdot_full, columns=[e.name for e in edges])
        df_mdot.insert(0, 'время_с', time)
        df_open = pd.DataFrame(open_full, columns=[e.name for e in edges])
        df_open.insert(0, 'время_с', time)
        out = (df_main, df_drossel, df_energy, nodes, edges, df_energy_edges, df_energy_groups, df_atm, df_p, df_mdot, df_open)
        if len(out) != 11:
            raise AssertionError(f'record_full output contract: expected 11 items, got {len(out)}')
        return out
    out = (df_main, df_drossel, df_energy, nodes, edges, df_energy_edges, df_energy_groups, df_atm)
    if len(out) != 8:
        raise AssertionError(f'output contract: expected 8 items, got {len(out)}')
    return out

def run_default_and_export_excel(output_path: str = 'результаты_полная_тесты_v3_camozzi_пружины.xlsx'):
    # Параметры (можно оптимизировать)
    params = {
        # Уставки адаптивности (ресивер 3) и питание Р2 из аккумулятора
        'давление_Pmin_питание_Ресивер2': P_ATM + 2e5,
        'давление_Pmin_сброс': P_ATM + 2e5,
        'давление_Pmid_сброс': P_ATM + 4e5,
        'давление_Pmax_предохран': P_ATM + 8e5,
        'начальное_давление_аккумулятора': P_ATM + 6e5,

        # Открытия дросселей SCO (0..1) = доля от максимального прохода по d_max выбранной модели
        'открытие_дросселя_Ц2_CAP_в_ROD': 0.35,
        'открытие_дросселя_Ц2_ROD_в_CAP': 0.35,
        'открытие_дросселя_выхлоп_Pmin': 0.30,
        'открытие_дросселя_выхлоп_Pmid': 0.45,
        'открытие_дросселя_выхлоп_Pmax': 0.70,

        # Нелинейная пружина: табличная добавочная сила относительно точки "середина хода"
        'пружина_таблица_ход_мм': [-125, -80, -40, -20, 0, 20, 50, 80, 125],
        'пружина_таблица_сила_Н': [-1200, -900, -500, -200, 0, 400, 1200, 2200, 4000],
        'пружина_масштаб': 1.0,
    }

    tests = {
        'инерция_крен_ay_step': {
            'ay_func': lambda t: 3.0 if t > 0.5 else 0.0,
            'road_func': lambda t: np.zeros(4),
            'описание': 'Ступень по боковому ускорению ay=3 м/с^2 после 0.5 с (имитация поворота).'
        },
        'инерция_тангаж_ax_step': {
            'ax_func': lambda t: 3.0 if t > 0.5 else 0.0,
            'road_func': lambda t: np.zeros(4),
            'описание': 'Ступень по продольному ускорению ax=3 м/с^2 после 0.5 с (торможение/разгон).'
        },
        'дорога_синфаза_sine_20мм_2Гц': {
            'road_func': lambda t: 0.02*np.sin(2*np.pi*2*t)*np.ones(4),
            'описание': 'Синфазная синусоида дороги 20 мм, 2 Гц, все колёса одинаково.'
        },
        'дорога_разнофаза_left_right_sine_20мм_2Гц': {
            'road_func': lambda t: 0.02*np.sin(2*np.pi*2*t)*np.array([1,-1,1,-1]),
            'описание': 'Разнофазная синусоида: левые +, правые - (креновое возбуждение).'
        },
        'дорога_диагональ_step_30мм': {
            'road_func': lambda t: (np.array([0.03,0.0,0.0,0.03]) if (1.0 < t < 1.3) else np.zeros(4)),
            'описание': 'Диагональный бугор: ЛП и ПЗ +30 мм на 0.3 с.'
        }
    }

    idx_atm = node_index['АТМ']
    P_N = float(params.get('P_N_Па', P_N_DEFAULT))
    T_N = float(params.get('T_N_К', T_N_DEFAULT))
    rho_N = P_N/(R_AIR*T_N)

    all_results = {}
    kpi_rows = []
    flows_rows = []
    energy_rows = []

    for name, test in tests.items():
        df_main, df_drossel, df_energy, nodes, edges, df_energy_edges, df_energy_groups, df_atm = simulate(params, test, dt=1e-3, t_end=3.0)
        all_results[name] = (df_main, df_drossel, df_energy, test.get('описание',''))

        phi_deg = df_main['крен_phi_рад'].to_numpy()*180/math.pi
        th_deg = df_main['тангаж_theta_рад'].to_numpy()*180/math.pi

        kpi_rows.append({
            'тест': name,
            'описание': test.get('описание',''),
            'макс|крен|_град': float(np.max(np.abs(phi_deg))),
            'макс|тангаж|_град': float(np.max(np.abs(th_deg))),
            'конечное_давление_Р1_бар_абс': float(df_main['давление_ресивер1_Па'].iloc[-1]/1e5),
            'конечное_давление_Р2_бар_абс': float(df_main['давление_ресивер2_Па'].iloc[-1]/1e5),
            'конечное_давление_Р3_бар_абс': float(df_main['давление_ресивер3_Па'].iloc[-1]/1e5),
            'конечное_давление_АКК_бар_абс': float(df_main['давление_аккумулятор_Па'].iloc[-1]/1e5),
            'энергия_дроссели_Дж': float(df_energy['энергия_рассеяна_Дж'].sum()),
        })

        dt_local = df_drossel['время_с'].iloc[1] - df_drossel['время_с'].iloc[0]
        for col in df_drossel.columns[1:]:
            m_abs = float(np.sum(np.abs(df_drossel[col].to_numpy()))*dt_local)
            Vn_l = m_abs / rho_N * 1000.0
            flows_rows.append({'тест': name, 'дроссель': col, 'расход_Нл': Vn_l})

        totE = df_energy['энергия_рассеяна_Дж'].sum()
        for _, row in df_energy.iterrows():
            energy_rows.append({
                'тест': name,
                'дроссель': row['дроссель'],
                'энергия_Дж': float(row['энергия_рассеяна_Дж']),
                'доля': float(row['энергия_рассеяна_Дж']/totE if totE>0 else 0)
            })

    df_kpi = pd.DataFrame(kpi_rows)
    df_flows = pd.DataFrame(flows_rows).pivot(index='дроссель', columns='тест', values='расход_Нл').reset_index()
    df_energy_all = pd.DataFrame(energy_rows)

        # Легенда (человеческая) + жёсткая привязка Camozzi по каждому месту схемы
    nodes_df = pd.DataFrame([{
        'узел': n.name,
        'тип_узла': n.kind,
        'объём_м3': float(n.V0),
        'угол': n.corner or '',
        'цилиндр': n.cyl or '',
        'полость': ('бесштоковая' if n.chamber == 'CAP' else 'штоковая') if n.chamber else ''
    } for n in nodes])

    edges_df = pd.DataFrame([{
        'элемент': e.name,
        'узел_вверх': nodes[e.n1].name,
        'узел_вниз': nodes[e.n2].name,
        'тип_элемента': e.kind,
        'Camozzi_код': e.camozzi_код,
        'площадь_эффективная_мм2': float(e.A)*1e6,
        'площадь_максимальная_мм2': (float(e.A_макс)*1e6) if (e.A_макс is not None) else '',
        'alpha_открытия': (float(e.alpha) if e.alpha is not None else ''),
        'перепад_открытия_Па': float(e.dp_crack) if e.dp_crack is not None else '',
        'уставка_Па': float(e.p_set) if e.p_set is not None else '',
        'группа': (e.group or '')
    } for e in edges])

    # Таблица пружины (для "живого" редактирования)
    spring_df = pd.DataFrame({
        'ход_delta_мм': params.get('пружина_таблица_ход_мм', [-125, -80, -40, -20, 0, 20, 50, 80, 125]),
        'сила_добавочная_Н': params.get('пружина_таблица_сила_Н', [-1200, -900, -500, -200, 0, 400, 1200, 2200, 4000]),
    })
    with pd.ExcelWriter(output_path, engine='openpyxl') as writer:
        df_kpi.to_excel(writer, sheet_name='KPI', index=False)
        df_flows.to_excel(writer, sheet_name='Расходы_дроссели_Нл', index=False)
        df_energy_all.to_excel(writer, sheet_name='Энергия_дроссели', index=False)
        nodes_df.to_excel(writer, sheet_name='Узлы', index=False)
        edges_df.to_excel(writer, sheet_name='Элементы', index=False)
        spring_df.to_excel(writer, sheet_name='Пружина', index=False)

        for test_name, (df_main, df_drossel, df_energy, descr) in all_results.items():
            base = re.sub(r'[^0-9A-Za-zА-Яа-я_]+','_', test_name)
            sheet_main = (base[:25] + '_t')[:31]
            sheet_flow = (base[:25] + '_q')[:31]
            df_main.to_excel(writer, sheet_name=sheet_main, index=False)
            df_drossel.to_excel(writer, sheet_name=sheet_flow, index=False)

    return output_path

if __name__ == '__main__':
    run_default_and_export_excel('результаты_полная_тесты_v3_camozzi_пружины.xlsx')
